// Conversion-matrix coverage: every registry route marked new in this branch
// runs against the fixtures in fixtures/conversion-matrix (regenerated by
// node fixtures/conversion-matrix/gen.mjs). Live-API tests (arXiv, DOI, ISBN,
// PMID) hit the real public endpoints; set E2E_SKIP_NETWORK=1 to skip them.
import { existsSync, mkdtempSync, readFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test, expect } from "../fixtures";
import {
  compileAndProbe,
  createBlankProject,
  readProjectText,
  setNextSavePath,
  waitLong,
  writeProjectText,
  type Page,
} from "../helpers";

const FIXTURES = fileURLToPath(new URL("../../fixtures/conversion-matrix", import.meta.url));
const fixture = (name: string) => join(FIXTURES, name);
const skipNetwork = process.env.E2E_SKIP_NETWORK === "1";

let scratch: string;
test.beforeAll(() => {
  scratch = mkdtempSync(join(tmpdir(), "conversion-matrix-"));
});

function projectState(page: Page) {
  return page.evaluate<{ main: string; engineId: string; paths: string[] }>(
    `import("/src/store/files.ts").then((m) => {
      const s = m.useFilesStore.getState();
      return {
        main: s.mainDoc,
        engineId: s.engine.id,
        paths: s.tree.map((f) => f.path),
      };
    })`,
  );
}

async function editorSource(page: Page): Promise<string> {
  return page.evaluate<string>(
    `import("/src/components/editor/cm/controller.ts").then((m) => {
      const view = m.getEditorView();
      return view ? view.state.doc.toString() : "";
    })`,
  );
}

async function goHome(page: Page) {
  await page.evaluate(`import("/src/store/files.ts").then((m) => m.useFilesStore.getState().closeProject())`);
  await waitLong(page, `!!document.querySelector('[data-testid="library"]')`, 15_000);
}

/** Import a file as a project of the given kind through the real feature. */
async function importFile(page: Page, path: string, target?: "latex" | "markdown" | "typst") {
  await page.evaluate(
    `import("/src/features/project-import.ts").then((m) =>
      m.importSelectedFile(${JSON.stringify(path)}, ${JSON.stringify(target ?? null)}))`,
  );
  await waitLong(page, `!!document.querySelector('[data-tour="project-editor"] .cm-content')`, 60_000);
}

async function exportThroughMenu(page: Page, label: string, destination: string) {
  await setNextSavePath(page, destination);
  await page.evaluate(
    `(() => {
      const button = document.querySelector('[aria-label="Export"]');
      if (!(button instanceof HTMLButtonElement)) throw new Error("Export control is unavailable");
      button.focus();
      button.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true }));
      return true;
    })()`,
  );
  await page.waitForFunction(
    `Array.from(document.querySelectorAll('[role="menuitem"]')).some(
      item => item.textContent?.trim() === ${JSON.stringify(label)}
    )`,
    10_000,
  );
  await page.getByText(label, { exact: true }).click();
  const deadline = Date.now() + 180_000;
  for (;;) {
    if (existsSync(destination) && statSync(destination).size > 0) return;
    if (Date.now() > deadline) throw new Error(`export did not finish: ${destination}`);
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
}

async function convertTable(page: Page, path: string, target: "latex" | "typst") {
  return page.evaluate<string>(
    `window.__e2eConvertTableFile(${JSON.stringify(path)}, { header: true, target: ${JSON.stringify(target)} })`,
  );
}

test.describe("LaTeX project exports (registry routes)", () => {
  test("imports the paper zip and compiles it", async ({ tauriPage }) => {
    test.setTimeout(300_000);
    await tauriPage.evaluate(
      `import("/src/store/files.ts").then((m) => m.useFilesStore.getState().importProject(${JSON.stringify(fixture("latex-paper.zip"))}))`,
    );
    await waitLong(tauriPage, `!!document.querySelector('[data-tour="project-editor"] .cm-content')`, 60_000);
    const state = await projectState(tauriPage);
    expect(state.main).toBe("main.tex");
    expect(state.engineId).toBe("latex");
    expect(state.paths).toContain("sections/method.tex");
    await compileAndProbe(tauriPage);
    await waitLong(tauriPage, `import("/src/store/compile.ts").then((m) => m.useCompileStore.getState().pdfBytes !== null)`, 120_000);
  });

  test("exports Typst, Word, MathML HTML, and Markdown", async ({ tauriPage }) => {
    test.setTimeout(300_000);
    await goHome(tauriPage);
    await tauriPage.evaluate(
      `import("/src/store/files.ts").then(async (m) => {
        const s = m.useFilesStore.getState();
        await s.refreshProjects();
        const paper = s.projects.find((p) => p.name.includes("latex-paper"));
        if (!paper) throw new Error("latex-paper project not found: " + s.projects.map((p) => p.name).join(", "));
        await m.useFilesStore.getState().openProject(paper.id);
      })`,
    );
    await waitLong(tauriPage, `!!document.querySelector('[data-tour="project-editor"] .cm-content')`, 60_000);

    const typ = join(scratch, "paper.typ");
    await exportThroughMenu(tauriPage, "Export as Typst (.typ)", typ);
    const typSource = readFileSync(typ, "utf8");
    expect(typSource).toContain("= Introduction");
    expect(typSource).toContain("=");
    expect(typSource.length).toBeGreaterThan(500);

    const docx = join(scratch, "paper.docx");
    await exportThroughMenu(tauriPage, "Export as Word (.docx)", docx);
    expect(readFileSync(docx).subarray(0, 2)).toEqual(new Uint8Array([0x50, 0x4b]));

    const html = join(scratch, "paper.html");
    await exportThroughMenu(tauriPage, "Export as HTML (MathML)", html);
    const htmlSource = readFileSync(html, "utf8");
    expect(htmlSource).toContain("<math");
    expect(htmlSource).toContain("Introduction");

    const md = join(scratch, "paper.md");
    await exportThroughMenu(tauriPage, "Export as Markdown (.md)", md);
    const mdSource = readFileSync(md, "utf8");
    expect(mdSource).toContain("# Introduction");
    expect(mdSource).toContain("$");
  });
});

test.describe("import routes (pandoc plan table)", () => {
  test("html to LaTeX, Markdown, and Typst projects", async ({ tauriPage }) => {
    test.setTimeout(240_000);
    await importFile(tauriPage, fixture("mathml-page.html"));
    let state = await projectState(tauriPage);
    expect(state.main).toBe("main.tex");
    let source = await editorSource(tauriPage);
    expect(source).toContain("\\section{");
    expect(source).toContain("Finite-time convergence");

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("mathml-page.html"), "markdown");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.md");
    expect(state.engineId).toBe("markdown");
    source = await editorSource(tauriPage);
    expect(source).toContain("# Finite-time convergence");

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("mathml-page.html"), "typst");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.typ");
    expect(state.engineId).toBe("typst");
    source = await editorSource(tauriPage);
    expect(source).toContain("= Finite-time convergence");
  });

  test("typst to LaTeX and Markdown projects", async ({ tauriPage }) => {
    test.setTimeout(240_000);
    await importFile(tauriPage, fixture("paper.typ"));
    let state = await projectState(tauriPage);
    expect(state.main).toBe("main.tex");
    let source = await editorSource(tauriPage);
    expect(source).toContain("documentclass");
    expect(source).toContain("Convergence of projected gradient descent");
    expect(source).toContain("epsilon");

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("paper.typ"), "markdown");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.md");
    source = await editorSource(tauriPage);
    expect(source).toContain("# Convergence of projected gradient descent");
    expect(source).toContain("$");
  });

  test("docx to LaTeX, Markdown, and Typst projects (OMML math survives)", async ({ tauriPage }) => {
    test.setTimeout(240_000);
    await importFile(tauriPage, fixture("docx-omml.docx"));
    let state = await projectState(tauriPage);
    expect(state.main).toBe("main.tex");
    let source = await editorSource(tauriPage);
    expect(source).toContain("mc^{2}");
    expect(source).toContain("\\footnote{");
    expect(state.paths.some((p) => p.startsWith("assets/"))).toBe(true);

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("docx-omml.docx"), "markdown");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.md");
    source = await editorSource(tauriPage);
    expect(source).toContain("$$");

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("docx-omml.docx"), "typst");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.typ");
    expect(state.engineId).toBe("typst");
  });

  test("markdown to LaTeX and Typst projects (citations, footnotes, math, mermaid)", async ({ tauriPage }) => {
    test.setTimeout(240_000);
    await importFile(tauriPage, fixture("math-citations.md"));
    let state = await projectState(tauriPage);
    expect(state.main).toBe("main.tex");
    let source = await editorSource(tauriPage);
    expect(source).toContain("\\footnote{");
    expect(source).toContain("vaswani2017attention");
    expect(source).toContain("Text layer?");

    await goHome(tauriPage);
    await importFile(tauriPage, fixture("math-citations.md"), "typst");
    state = await projectState(tauriPage);
    expect(state.main).toBe("main.typ");
    source = await editorSource(tauriPage);
    expect(source).toContain("= Setup");
    expect(source).toContain("$");
  });
});

test.describe("spreadsheet tables (G17)", () => {
  test("csv to LaTeX escapes every special exactly once", async ({ tauriPage }) => {
    const latex = await convertTable(tauriPage, fixture("messy.csv"), "latex");
    expect(latex).toContain("\\toprule");
    expect(latex).toContain("\\midrule");
    expect(latex).toContain("\\bottomrule");
    expect(latex).toContain("\\textbf{Name}");
    // The full escaping chain, each exactly once per cell.
    expect(latex).toContain("a\\&b\\%c\\$d\\#e\\_f\\{g\\}h");
    expect(latex).toContain("\\textasciitilde{}i\\textasciicircum{}j\\textbackslash{}k");
    // No double escapes from the inserted commands.
    expect(latex).not.toContain("textbackslash\\{");
    // Quoted commas stay one cell; newlines inside quotes are flattened.
    expect(latex).toContain("Smith, Jane");
    expect(latex).toContain("line one line two");
    // Unicode passes through for the XeTeX default engine.
    expect(latex).toContain("αβγ");
  });

  test("csv to Typst emits a table with a header", async ({ tauriPage }) => {
    const typst = await convertTable(tauriPage, fixture("messy.csv"), "typst");
    expect(typst).toContain("#table(");
    expect(typst).toContain("table.header([*Name*]");
    expect(typst).toContain("[Smith, Jane]");
  });

  test("xlsx honors merged cells and formula results", async ({ tauriPage }) => {
    const latex = await convertTable(tauriPage, fixture("messy.xlsx"), "latex");
    // Merged cell value lands once, its continuation reads empty.
    expect(latex).toContain("merged-right &");
    // The formula exports its cached result, not its expression.
    expect(latex).toContain("49");
    expect(latex).not.toContain("SUM(D2");
  });
});

test.describe("equation export (G16)", () => {
  test("renders SVG through MathJax and rejects broken TeX", async ({ tauriPage }) => {
    const svg = await tauriPage.evaluate<string>(
      `window.__e2eEquationSvg("E = mc^2", true)`,
    );
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg).toContain("<path");
    const aligned = await tauriPage.evaluate<string>(
      `window.__e2eEquationSvg("\\\\begin{aligned} a &= b + c \\\\\\\\ d &= e \\\\end{aligned}", true)`,
    );
    expect(aligned).toContain("<path");
    const matrix = await tauriPage.evaluate<string>(
      `window.__e2eEquationSvg("\\\\begin{pmatrix} 1 & 2 \\\\\\\\ 3 & 4 \\\\end{pmatrix}", true)`,
    );
    expect(matrix).toContain("<path");
    await expect(
      tauriPage.evaluate(`window.__e2eEquationSvg("\\\\begin{aligned}", true)`),
    ).rejects.toThrow();
  });
});

test.describe("bibtex cleaner (G6)", () => {
  test("dry run reports the plan and apply rewrites the library", async ({ tauriPage }) => {
    test.setTimeout(120_000);
    await createBlankProject(tauriPage, "cleaner-fixture");
    const dirty = readFileSync(fixture("dirty.bib"), "utf8");
    await writeProjectText(tauriPage, "references.bib", dirty);

    const clean = (apply: boolean) =>
      tauriPage.evaluate(
        `import("/src/lib/tauri.ts").then((m) =>
          import("/src/store/files.ts").then((f) =>
            m.cleanBibtexLibrary(f.useFilesStore.getState().projectId, "references.bib", ${apply})))`,
      );
    const outcome = await clean(false);
    expect(outcome.entriesBefore).toBe(5);
    expect(outcome.entriesAfter).toBe(3);
    const kinds = outcome.actions.map((a: { kind: string }) => a.kind);
    expect(kinds).toContain("removed-duplicate");
    expect(kinds).toContain("renamed-key");
    expect(outcome.cleaned).toContain("Shazeer");

    const applied = await clean(true);
    expect(applied.applied).toBe(true);
    expect(await readProjectText(tauriPage, "references.bib")).toContain("vaswani2017attention");
  });
});

test.describe("statistics calculators (G39)", () => {
  test("matches reference values from the statrs backend", async ({ tauriPage }) => {
    const p = await tauriPage.evaluate(
      `import("/src/lib/tauri.ts").then((m) => m.statsPValue("t-two", 2.34, 28))`,
    );
    expect(Math.abs(p.p - 0.02664)).toBeLessThan(1e-4);
    const n = await tauriPage.evaluate(
      `import("/src/lib/tauri.ts").then((m) => m.statsSampleSize(50, 5, 95, 1000))`,
    );
    expect(n.infinitePopulation).toBe(385);
    expect(n.finitePopulation).toBe(278);
    const ci = await tauriPage.evaluate(
      `import("/src/lib/tauri.ts").then((m) => m.statsConfidenceInterval("mean", 95, { mean: 100, sd: 15, n: 9 }))`,
    );
    expect(Math.abs(ci.criticalValue - 2.306)).toBeLessThan(1e-3);
    expect(Math.abs(ci.marginOfError - 11.53)).toBeLessThan(1e-2);
  });
});

test.describe("pdf fixtures", () => {
  test("text-layer pdf converts; image-only pdf reports no-text-layer (G2 deferred)", async ({ tauriPage }) => {
    const run = (name: string) =>
      tauriPage.evaluate(
        `import("/packages/pdf-to-latex/src/pdf-adapter.ts").then(async (adapter) => {
          const convert = await import("/packages/pdf-to-latex/src/index.ts");
          const bytes = Uint8Array.from(atob(${JSON.stringify(
            readFileSync(fixture(name)).toString("base64"),
          )}), (c) => c.charCodeAt(0));
          const { pages } = await adapter.extractPagesForConvert(bytes);
          return convert.convertPages(pages, {});
        })`,
      );
    const textResult = await run("text-layer.pdf");
    expect(textResult.tex).toContain("Convergence of Iterated Maps");
    const scanResult = await run("image-only.pdf");
    // G2 is deferred: the pipeline says which pages have no text layer.
    expect(
      scanResult.report.notes.some(
        (note: { kind: string }) => note.kind === "no-text-layer",
      ),
    ).toBe(true);
  });
});

test.describe("live identifier lookups (G7)", () => {
  test.skip(skipNetwork, "network lookups skipped (E2E_SKIP_NETWORK=1)");

  test("doi, isbn, and pmid resolve to real bibtex", async ({ tauriPage }) => {
    test.setTimeout(120_000);
    const doi = await tauriPage.evaluate(
      `import("/src/features/citation.ts").then((m) => m.resolveCitation("10.1093/comjnl/27.2.97"))`,
    );
    expect(doi.bibtex ?? "").toMatch(/@article\{/);
    expect(doi.bibtex ?? "").toContain("Literate Programming");

    const isbn = await tauriPage.evaluate(
      `import("/src/features/citation.ts").then((m) => m.resolveCitation("978-0-262-03561-3"))`,
    );
    expect(isbn.bibtex ?? "").toMatch(/@book\{/);
    expect(isbn.bibtex ?? "").toContain("Deep Learning");

    const pmid = await tauriPage.evaluate(
      `import("/src/features/citation.ts").then((m) => m.resolveCitation("32172672"))`,
    );
    expect(pmid.bibtex ?? "").toMatch(/@article\{/);
    expect(pmid.bibtex ?? "").toContain("pmid = {32172672}");
  });

  test("an arxiv e-print round-trips into a compiling project", async ({ tauriPage }) => {
    test.setTimeout(480_000);
    await tauriPage.evaluate(
      `import("/src/features/project-import.ts").then((m) => m.importArxivPaper("2106.09685"))`,
    );
    await waitLong(tauriPage, `!!document.querySelector('[data-tour="project-editor"] .cm-content')`, 180_000);
    const state = await projectState(tauriPage);
    expect(state.main.endsWith(".tex")).toBe(true);
    expect(state.engineId).toBe("latex");
    await compileAndProbe(tauriPage);
    await waitLong(tauriPage, `import("/src/store/compile.ts").then((m) => m.useCompileStore.getState().pdfBytes !== null)`, 240_000);
  });
});
