// Generated by scripts/i18n/gen-types.ts from src/i18n/locales/en. Do not edit.
import type ai from "./locales/en/ai.json";
import type catalog from "./locales/en/catalog.json";
import type common from "./locales/en/common.json";
import type core from "./locales/en/core.json";
import type diagram from "./locales/en/diagram.json";
import type editor from "./locales/en/editor.json";
import type errors from "./locales/en/errors.json";
import type intelligence from "./locales/en/intelligence.json";
import type library from "./locales/en/library.json";
import type native from "./locales/en/native.json";
import type onboarding from "./locales/en/onboarding.json";
import type preflight from "./locales/en/preflight.json";
import type preview from "./locales/en/preview.json";
import type references from "./locales/en/references.json";
import type researchTools from "./locales/en/researchTools.json";
import type settings from "./locales/en/settings.json";
import type shell from "./locales/en/shell.json";
import type symbols from "./locales/en/symbols.json";
import type templates from "./locales/en/templates.json";
import type usage from "./locales/en/usage.json";
import type workspace from "./locales/en/workspace.json";

export interface Resources {
  "ai": typeof ai;
  "catalog": typeof catalog;
  "common": typeof common;
  "core": typeof core;
  "diagram": typeof diagram;
  "editor": typeof editor;
  "errors": typeof errors;
  "intelligence": typeof intelligence;
  "library": typeof library;
  "native": typeof native;
  "onboarding": typeof onboarding;
  "preflight": typeof preflight;
  "preview": typeof preview;
  "references": typeof references;
  "researchTools": typeof researchTools;
  "settings": typeof settings;
  "shell": typeof shell;
  "symbols": typeof symbols;
  "templates": typeof templates;
  "usage": typeof usage;
  "workspace": typeof workspace;
}

export const NAMESPACE_NAMES = ["ai","catalog","common","core","diagram","editor","errors","intelligence","library","native","onboarding","preflight","preview","references","researchTools","settings","shell","symbols","templates","usage","workspace"] as const;
