// @vitest-environment jsdom
import { act, cleanup, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import earlySource from "@/lib/__fixtures__/tikz-v026-generated.tex?raw";
import legacySource from "@/lib/__fixtures__/tikz-v0313-generated.tex?raw";
import type { DiagramModel } from "@oleafly/latex";
import { diagramLanguage } from "@oleafly/diagram";

const mocks = vi.hoisted(() => ({
  read: vi.fn(), write: vi.fn(), bytes: vi.fn(async () => undefined),
  renderFigure: vi.fn(async () => ({ svg: "<svg/>", pngBase64: "iVBORw0KGgo=" })),
  change: null as null | ((model: DiagramModel) => void),
  model: null as DiagramModel | null,
  readOnly: false,
}));
vi.mock("@/lib/tauri", () => ({
  readFileContent: mocks.read, writeFileContent: mocks.write, writeProjectBytes: mocks.bytes,
  projectMutationGeneration: vi.fn(async () => 0), mcpSetActiveProject: vi.fn(async () => {}),
  listFiles: vi.fn(async () => []), listFileTree: vi.fn(async () => ({ entries: [], truncated: false })), gitShow: vi.fn(async () => ""),
}));
vi.mock("@/components/diagram/diagram-kit", () => ({ KIT: {} }));
vi.mock("@/components/diagram/mermaid-render", () => ({ renderMermaidFigure: mocks.renderFigure }));
vi.mock("@oleafly/diagram", async () => {
  const { createContext } = await import("react");
  const actual = await vi.importActual<typeof import("@oleafly/diagram")>("@oleafly/diagram");
  return { ...actual, DiagramKitContext: createContext({}), DiagramCanvas: ({ model, onChange, readOnly }: {
    model: DiagramModel; onChange: (model: DiagramModel) => void; readOnly: boolean;
  }) => {
    mocks.model = model; mocks.change = onChange; mocks.readOnly = readOnly;
    return <div data-testid="canvas" />;
  } };
});
import DiagramMainFileView from "./DiagramMainFileView";
import { useFilesStore } from "@/store/files";
import { standaloneDiagramSource } from "@/lib/diagram-source";

beforeEach(() => { mocks.write.mockClear(); mocks.model = null; mocks.change = null; });
afterEach(async () => { cleanup(); await useFilesStore.getState().closeProject(); await vi.dynamicImportSettled(); });

function currentModel(): DiagramModel {
  if (!mocks.model) throw new Error("Canvas did not load a model");
  return mocks.model;
}
function changeModel(model: DiagramModel) {
  if (!mocks.change) throw new Error("Canvas did not register its change handler");
  mocks.change(model);
}

async function open(source: string, path = "main.tex") {
  mocks.read.mockResolvedValue(source);
  mocks.write.mockResolvedValue({ generation: 1 });
  useFilesStore.setState({ projectId: "diagram", activePath: path, mainDoc: path, projectKind: "diagram",
    files: { [path]: { content: source, dirty: false } }, openTabs: [path] });
  render(<DiagramMainFileView projectId="diagram" path={path} />);
  await screen.findByTestId("canvas");
}

it("never overwrites unsupported TikZ or its custom preamble on a canvas change", async () => {
  const source = String.raw`\documentclass{standalone}
\usepackage{tikz}
\newcommand{\studyname}{Study}
\begin{document}
\begin{tikzpicture}
\node (a) at (0,0) {\studyname};
\foreach \x in {1,2,3} {\draw (\x,0) circle (0.2);}
\end{tikzpicture}
\end{document}`;
  await open(source);
  expect(mocks.readOnly).toBe(true);
  expect(screen.getByRole("status")).toHaveTextContent("read-only preview");
  const next = structuredClone(currentModel()); next.nodes[0].x += 40;
  act(() => changeModel(next));
  await useFilesStore.getState().flushForQuit();
  expect(useFilesStore.getState().files["main.tex"].content).toBe(source);
  expect(mocks.write).not.toHaveBeenCalled();
});

it("keeps 0.3.13 drawings editable, preserves model identity for undo and retains background", async () => {
  const source = legacySource;
  await open(source);
  expect(mocks.readOnly).toBe(false);
  const next = structuredClone(currentModel()); delete next.background; next.nodes[0].x += 40;
  act(() => changeModel(next));
  expect(mocks.model).toBe(next);
  const second = structuredClone(next); second.nodes[0].x += 40;
  act(() => changeModel(second));
  await useFilesStore.getState().flushForQuit();
  expect(useFilesStore.getState().files["main.tex"].content).toBe(standaloneDiagramSource({ ...second, background: "#ffffff" }));
  expect(mocks.write).toHaveBeenCalled();
});

it("does not overwrite source changed outside the current canvas model", async () => {
  const source = legacySource;
  await open(source);
  const changed = source.replace("\\end{document}", "% keep this comment\n\\end{document}");
  useFilesStore.setState({ files: { "main.tex": { content: changed, dirty: false } } });
  const next = structuredClone(currentModel()); next.nodes[0].x += 40;
  act(() => changeModel(next));
  await waitFor(() => expect(mocks.readOnly).toBe(true));
  expect(useFilesStore.getState().files["main.tex"].content).toBe(changed);
  expect(mocks.write).not.toHaveBeenCalled();
});

it("opens drawings generated by 0.2.6 and upgrades them only after an edit", async () => {
  await open(earlySource);
  expect(mocks.readOnly).toBe(false);
  expect(mocks.write).not.toHaveBeenCalled();
  const next = structuredClone(currentModel());
  next.nodes[1].x += 40;
  act(() => changeModel(next));
  await useFilesStore.getState().flushForQuit();
  expect(useFilesStore.getState().files["main.tex"].content).toBe(standaloneDiagramSource(next));
});

it("keeps customized 0.2.6 source read-only", async () => {
  const source = earlySource.replace("\\begin{document}", "\\usepackage{amsmath}\n\\begin{document}");
  await open(source);
  expect(mocks.readOnly).toBe(true);
  await useFilesStore.getState().flushForQuit();
  expect(mocks.write).not.toHaveBeenCalled();
});

const TYPST_DRAWING: DiagramModel = {
  version: 1,
  nodes: [
    { id: "a", shape: "rectangle", x: 0, y: 0, w: 80, h: 40, label: "A", stroke: "#1e293b" },
    { id: "b", shape: "circle", x: 160, y: 0, w: 40, h: 40, label: "B", fill: "#cfe8f8" },
  ],
  edges: [{ id: "e", source: "a", target: "b", routing: "straight", arrow: "forward", style: "solid" }],
};

it("draws a Typst diagram project and writes canvas edits back as a standalone .typ", async () => {
  const typst = diagramLanguage("typst");
  await typst.load();
  const source = typst.standaloneSource({ ...TYPST_DRAWING, background: "#ffffff" });
  await open(source, "main.typ");
  expect(mocks.readOnly).toBe(false);
  expect(currentModel()).toEqual(TYPST_DRAWING);
  const next = structuredClone(currentModel()); next.nodes[1].x += 40;
  act(() => changeModel(next));
  const written = useFilesStore.getState().files["main.typ"].content;
  expect(written).toBe(typst.standaloneSource({ ...next, background: "#ffffff" }));
  expect(written.split("\n")[0]).toBe('#set page(width: auto, height: auto, margin: 4pt, fill: rgb("#ffffff"))');
});

it("keeps hand-written fletcher code it cannot draw when the canvas edits a Typst diagram", async () => {
  const source = [
    "#set page(width: auto, height: auto, margin: 4pt)",
    '#import "@preview/fletcher:0.5.8": diagram, node, edge',
    "#diagram(",
    "  spacing: 3em,",
    "  node((0cm, 0cm), [A], name: <a>, width: 2cm, height: 1cm),",
    "  node((4cm, 0cm), [B], name: <b>, width: 2cm, height: 1cm),",
    '  edge(<a>, <b>, "->"),',
    ")",
  ].join("\n");
  await open(source, "main.typ");
  expect(mocks.readOnly).toBe(false);
  const next = structuredClone(currentModel()); next.nodes[1].y += 40;
  act(() => changeModel(next));
  const written = useFilesStore.getState().files["main.typ"].content;
  expect(written).toContain("  spacing: 3em,");
  expect(written).toContain("  node((0cm, 0cm), [A], name: <a>, width: 2cm, height: 1cm),");
  expect(written).toContain('  edge(<a>, <b>, "->"),');
  expect(written).not.toContain("node((4cm, 0cm), [B]");
});

it("says a Typst file without a fletcher diagram cannot be drawn", async () => {
  mocks.read.mockResolvedValue("= Notes");
  useFilesStore.setState({ projectId: "diagram", activePath: "main.typ", mainDoc: "main.typ", projectKind: "diagram",
    files: { "main.typ": { content: "= Notes", dirty: false } }, openTabs: ["main.typ"] });
  render(<DiagramMainFileView projectId="diagram" path="main.typ" />);
  expect(await screen.findByText(/nothing in this code the canvas can draw/i)).toBeInTheDocument();
});

it("draws a Markdown diagram project, keeps the text around the block and refreshes the PDF figure", async () => {
  const mermaid = diagramLanguage("mermaid");
  const block = mermaid.standaloneSource(TYPST_DRAWING);
  const source = `# Pipeline\n\n${block}\nMore notes.\n`;
  await open(source, "main.md");
  expect(mocks.readOnly).toBe(false);
  expect(currentModel()).toEqual(TYPST_DRAWING);
  vi.useFakeTimers();
  try {
    const next = structuredClone(currentModel()); next.nodes[0].label = "Input";
    act(() => changeModel(next));
    const written = useFilesStore.getState().files["main.md"].content;
    expect(written.startsWith("# Pipeline\n\n```mermaid\n")).toBe(true);
    expect(written.endsWith("```\n\nMore notes.\n")).toBe(true);
    expect(written).toBe(`# Pipeline\n\n${mermaid.standaloneSource(next)}\nMore notes.\n`);
    await act(async () => { await vi.advanceTimersByTimeAsync(900); });
  } finally {
    vi.useRealTimers();
  }
  await waitFor(() => expect(mocks.bytes).toHaveBeenCalledWith("diagram", expect.stringMatching(/^figures\/mermaid-[0-9a-f]{16}\.png$/), expect.any(String)));
});
