/**
 * Types for the normalized LaTeX Workshop corpus generated by
 * scripts/latex-intelligence-extract.mjs into packages/latex-intelligence/data.
 *
 * All snippets use the CodeMirror snippet() grammar (`${N}` / `${N:placeholder}`).
 */

export interface CoreCommand {
  name: string;
  snippet?: string;
  detail?: string;
  documentation?: string;
}

export interface CoreEnvironment {
  name: string;
  snippet?: string;
}

/** data/core.json: default commands and environments. */
export interface CoreCatalog {
  commands: CoreCommand[];
  environments: CoreEnvironment[];
}

/** A macro contributed by a package or class. */
export interface CorpusMacro {
  name: string;
  snippet?: string;
  detail?: string;
  documentation?: string;
  unusual?: boolean;
  /** Lookup keys into the owning catalog's `keys` map. */
  keys?: string[];
  /** Which argument of the snippet takes key=value options. */
  keyPos?: number;
}

/** An environment contributed by a package or class. */
export interface CorpusEnvironment {
  name: string;
  snippet?: string;
  detail?: string;
  unusual?: boolean;
  keys?: string[];
  keyPos?: number;
}

/** data/packages/<name>.json: one package (or `class-<name>` class) catalog. */
export interface PackageCatalog {
  /** Names of packages this one loads, including option-conditional ones. */
  deps: string[];
  macros: CorpusMacro[];
  envs: CorpusEnvironment[];
  /** Key-value completions, addressed by `CorpusMacro.keys`. */
  keys: Record<string, string[]>;
  args: string[];
  /** Package/class option completions (legacy CWL-format files only). */
  options?: string[];
}

/** data/package-names.json and data/class-names.json. */
export interface NameList {
  names: string[];
  /** Human-readable descriptions; names with no description are omitted. */
  details: Record<string, string>;
}

/** data/manifest.json: provenance of the vendored corpus. */
export interface Manifest {
  source: string;
  commit: string;
  license: string;
  generatedBy: string;
  files: Record<string, { from: string[] }>;
  notices: string[];
}
