import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../../", import.meta.url).pathname;
const englishDir = join(root, "src/i18n/locales/en");
const outputPath = join(root, "src/i18n/resources-types.d.ts");

const namespaces = readdirSync(englishDir)
  .filter((name) => name.endsWith(".json"))
  .map((name) => name.slice(0, -".json".length))
  .sort();

const identifier = (namespace: string) => namespace.replace(/[^A-Za-z0-9_]/g, "_");

const lines = [
  "// Generated by scripts/i18n/gen-types.ts from src/i18n/locales/en. Do not edit.",
  ...namespaces.map((ns) => `import type ${identifier(ns)} from "./locales/en/${ns}.json";`),
  "",
  "export interface Resources {",
  ...namespaces.map((ns) => `  ${JSON.stringify(ns)}: typeof ${identifier(ns)};`),
  "}",
  "",
  `export const NAMESPACE_NAMES = ${JSON.stringify(namespaces)} as const;`,
  "",
];
const content = lines.join("\n");

if (process.argv.includes("--check")) {
  let existing = "";
  try {
    existing = readFileSync(outputPath, "utf8");
  } catch {
    existing = "";
  }
  if (existing !== content) {
    console.error("src/i18n/resources-types.d.ts is stale. Run: pnpm i18n:types");
    process.exit(1);
  }
  console.log("i18n types are current");
} else {
  writeFileSync(outputPath, content);
  console.log(`wrote ${namespaces.length} namespaces to src/i18n/resources-types.d.ts`);
}
