import { EditorView } from "@codemirror/view";

const UI_FONT = "var(--font-sans, ui-sans-serif, system-ui, sans-serif)";

const SELECTED_TINT = "color-mix(in oklch, var(--primary) 12%, transparent)";

const ACTIVE_TINT = "color-mix(in oklch, var(--primary) 18%, transparent)";

const HANDLE_COLOR = "color-mix(in oklch, var(--muted-foreground) 35%, transparent)";

const HANDLE_HOVER = "color-mix(in oklch, var(--primary) 55%, transparent)";

const RULE_COLOR = "color-mix(in oklch, var(--foreground) 75%, transparent)";

const DASHED_COLOR = "color-mix(in oklch, var(--muted-foreground) 45%, transparent)";

const SHADOW = "0 4px 14px -4px rgba(0, 0, 0, 0.3)";

export const tableTheme = EditorView.theme({
  ".ofl-visual-table-widget": {
    position: "relative",
    padding: "6px 0",
    cursor: "default",
  },
  ".ofl-visual-table-frame": {
    position: "relative",
  },
  ".ofl-visual-table-grid": {
    tableLayout: "fixed",
    borderCollapse: "collapse",
    margin: "0 auto",
    userSelect: "none",
    WebkitUserSelect: "none",
    outline: "none",
    maxWidth: "100%",
  },
  ".ofl-visual-table-cell": {
    border: `1px dashed ${DASHED_COLOR}`,
    minWidth: "40px",
    height: "30px",
    padding: "2px 0.35em",
    verticalAlign: "top",
    outline: "none",
    overflowWrap: "anywhere",
  },
  ".ofl-visual-table-cell-editing": {
    padding: "0",
  },
  ".ofl-visual-table-cell-selected": {
    backgroundColor: SELECTED_TINT,
  },
  ".ofl-visual-table-cell-left": { textAlign: "left" },
  ".ofl-visual-table-cell-center": { textAlign: "center" },
  ".ofl-visual-table-cell-right": { textAlign: "right" },
  ".ofl-visual-table-cell-paragraph": { textAlign: "justify" },
  ".ofl-visual-table-cell-border-left": { borderLeft: `1px solid ${RULE_COLOR}` },
  ".ofl-visual-table-cell-border-right": { borderRight: `1px solid ${RULE_COLOR}` },
  ".ofl-visual-table-cell-border-top": { borderTop: `1px solid ${RULE_COLOR}` },
  ".ofl-visual-table-cell-border-bottom": { borderBottom: `1px solid ${RULE_COLOR}` },
  ".ofl-visual-table-cell-rule-double": { borderTopStyle: "double", borderTopWidth: "3px" },
  ".ofl-visual-table-cell-text": {
    whiteSpace: "pre-wrap",
    overflow: "hidden",
  },
  ".ofl-visual-table-cell-input": {
    display: "block",
    width: "100%",
    minHeight: "100%",
    boxSizing: "border-box",
    padding: "2px 0.35em",
    margin: "0",
    font: "inherit",
    color: "inherit",
    textAlign: "inherit",
    lineHeight: "inherit",
    backgroundColor: "var(--background)",
    border: "1px solid var(--ring)",
    borderRadius: "0",
    outline: "none",
    resize: "none",
    overflow: "hidden",
  },
  ".ofl-visual-table-handle": {
    padding: "0",
    border: "none",
    position: "relative",
    cursor: "pointer",
  },
  ".ofl-visual-table-handle::after": {
    content: '""',
    display: "block",
    position: "absolute",
    borderRadius: "3px",
    backgroundColor: HANDLE_COLOR,
  },
  ".ofl-visual-table-handle:hover::after": {
    backgroundColor: HANDLE_HOVER,
  },
  ".ofl-visual-table-handle-active::after": {
    backgroundColor: "var(--primary)",
  },
  ".ofl-visual-table-handle-row": {
    width: "18px",
  },
  ".ofl-visual-table-handle-row::after": {
    top: "4px",
    bottom: "4px",
    right: "6px",
    width: "4px",
  },
  ".ofl-visual-table-handle-column": {
    height: "18px",
  },
  ".ofl-visual-table-handle-column::after": {
    left: "4px",
    right: "4px",
    bottom: "6px",
    height: "4px",
  },
  ".ofl-visual-table-corner": {
    border: "none",
    padding: "0",
  },
  ".ofl-visual-table-widths td": {
    border: "none",
    padding: "0 0 4px",
    textAlign: "center",
  },
  ".ofl-visual-table-width-badge": {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    maxWidth: "100%",
    padding: "1px 6px",
    border: "none",
    borderRadius: "999px",
    backgroundColor: "var(--muted)",
    color: "var(--muted-foreground)",
    fontFamily: UI_FONT,
    fontSize: "11px",
    lineHeight: "16px",
    cursor: "pointer",
    outline: "none",
  },
  ".ofl-visual-table-width-badge:hover": {
    backgroundColor: "var(--accent)",
    color: "var(--accent-foreground)",
  },
  ".ofl-visual-table-width-badge span": {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".ofl-visual-table-toolbar": {
    position: "absolute",
    top: "0",
    left: "0",
    right: "0",
    margin: "0 auto",
    width: "max-content",
    maxWidth: "100%",
    transform: "translateY(calc(-100% - 8px))",
    zIndex: "152",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "2px",
    padding: "4px",
    borderRadius: "var(--radius-md, 8px)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow: SHADOW,
    fontFamily: UI_FONT,
    fontSize: "12px",
    lineHeight: "1.2",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  ".ofl-visual-table-group": {
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    paddingRight: "6px",
    marginRight: "6px",
    borderRight: "1px solid var(--border)",
  },
  ".ofl-visual-table-group:last-child": {
    paddingRight: "0",
    marginRight: "0",
    borderRight: "none",
  },
  ".ofl-visual-table-button": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "2px",
    height: "28px",
    minWidth: "28px",
    padding: "0 4px",
    margin: "0",
    border: "none",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    outline: "none",
  },
  ".ofl-visual-table-button:hover": {
    backgroundColor: "var(--accent)",
  },
  ".ofl-visual-table-button[aria-pressed='true'], .ofl-visual-table-button[aria-expanded='true']": {
    backgroundColor: ACTIVE_TINT,
  },
  ".ofl-visual-table-button:disabled": {
    opacity: "0.35",
    cursor: "default",
    backgroundColor: "transparent",
  },
  ".ofl-visual-table-select": {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "6px",
    height: "28px",
    minWidth: "120px",
    padding: "0 6px 0 8px",
    margin: "0",
    border: "1px solid var(--border)",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    whiteSpace: "nowrap",
    cursor: "pointer",
    outline: "none",
  },
  ".ofl-visual-table-select:hover": {
    backgroundColor: "var(--accent)",
  },
  ".ofl-visual-table-select:disabled": {
    opacity: "0.5",
    cursor: "default",
    backgroundColor: "transparent",
  },
  ".ofl-visual-table-menu-host": {
    position: "relative",
    display: "inline-flex",
  },
  ".ofl-visual-table-menu": {
    position: "absolute",
    top: "calc(100% + 4px)",
    left: "0",
    zIndex: "153",
    minWidth: "190px",
    display: "flex",
    flexDirection: "column",
    padding: "4px",
    borderRadius: "var(--radius-md, 8px)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow: SHADOW,
  },
  ".ofl-visual-table-menu-item": {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    padding: "6px 8px",
    margin: "0",
    border: "none",
    borderRadius: "4px",
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: "pointer",
    outline: "none",
  },
  ".ofl-visual-table-menu-item:hover": {
    backgroundColor: "var(--accent)",
  },
  ".ofl-visual-table-menu-item[aria-checked='true']": {
    backgroundColor: SELECTED_TINT,
  },
  ".ofl-visual-table-menu-item:disabled": {
    opacity: "0.35",
    cursor: "default",
    backgroundColor: "transparent",
  },
  ".ofl-visual-table-menu-label": {
    flex: "1 1 auto",
  },
  ".ofl-visual-table-menu-separator": {
    border: "0",
    height: "1px",
    margin: "4px 2px",
    backgroundColor: "var(--border)",
  },
  ".ofl-visual-table-icon": {
    width: "16px",
    height: "16px",
    flex: "0 0 auto",
  },
  ".ofl-visual-table-backdrop": {
    position: "fixed",
    inset: "0",
    zIndex: "1000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
  },
  ".ofl-visual-table-backdrop-close": {
    position: "absolute",
    inset: "0",
    margin: "0",
    padding: "0",
    border: "0",
    backgroundColor: "transparent",
    cursor: "default",
  },
  ".ofl-visual-table-dialog": {
    position: "relative",
    margin: "0",
    height: "auto",
    width: "min(440px, 92vw)",
    maxHeight: "85vh",
    overflow: "auto",
    padding: "16px 18px",
    borderRadius: "10px",
    border: "1px solid var(--border)",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow: "0 12px 40px -10px rgba(0, 0, 0, 0.45)",
    fontFamily: UI_FONT,
    fontSize: "13px",
    lineHeight: "1.5",
  },
  ".ofl-visual-table-dialog h2": {
    margin: "0 0 10px",
    fontSize: "15px",
    fontWeight: "600",
  },
  ".ofl-visual-table-dialog h3": {
    margin: "12px 0 4px",
    fontSize: "13px",
    fontWeight: "600",
  },
  ".ofl-visual-table-dialog p": {
    margin: "0 0 6px",
  },
  ".ofl-visual-table-dialog ul": {
    margin: "0 0 6px",
    paddingLeft: "18px",
  },
  ".ofl-visual-table-dialog code": {
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: "12px",
    padding: "0 3px",
    borderRadius: "3px",
    backgroundColor: "var(--muted)",
  },
  ".ofl-visual-table-dialog-actions": {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    marginTop: "14px",
  },
  ".ofl-visual-table-dialog-button": {
    height: "30px",
    padding: "0 12px",
    border: "1px solid var(--border)",
    borderRadius: "6px",
    backgroundColor: "var(--secondary)",
    color: "var(--secondary-foreground)",
    font: "inherit",
    cursor: "pointer",
    outline: "none",
  },
  ".ofl-visual-table-dialog-button:hover": {
    backgroundColor: "var(--accent)",
  },
  ".ofl-visual-table-dialog-button-primary": {
    backgroundColor: "var(--primary)",
    color: "var(--primary-foreground)",
    borderColor: "var(--primary)",
  },
  ".ofl-visual-table-dialog-button-primary:hover": {
    backgroundColor: "color-mix(in oklch, var(--primary) 85%, var(--background))",
  },
  ".ofl-visual-table-fields": {
    display: "flex",
    gap: "8px",
    alignItems: "flex-end",
  },
  ".ofl-visual-table-field": {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    flex: "1 1 auto",
  },
  ".ofl-visual-table-field-label": {
    fontSize: "12px",
    color: "var(--muted-foreground)",
  },
  ".ofl-visual-table-input": {
    height: "30px",
    padding: "0 8px",
    border: "1px solid var(--border)",
    borderRadius: "6px",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    font: "inherit",
    outline: "none",
    boxSizing: "border-box",
    width: "100%",
  },
  ".ofl-visual-table-input:focus": {
    borderColor: "var(--ring)",
  },
  ".ofl-visual-table-hint": {
    margin: "8px 0 0",
    fontSize: "12px",
    color: "var(--muted-foreground)",
  },
  ".ofl-visual-table-error": {
    margin: "4px 0",
    padding: "10px 12px",
    borderRadius: "var(--radius-md, 8px)",
    border: "1px solid var(--border)",
    backgroundColor: "var(--muted)",
    color: "var(--muted-foreground)",
    fontFamily: UI_FONT,
    fontSize: "12px",
    lineHeight: "1.5",
  },
  ".ofl-visual-table-error-title": {
    fontWeight: "600",
    color: "var(--foreground)",
  },
  ".ofl-visual-table-error-action": {
    marginTop: "6px",
    padding: "0",
    border: "none",
    background: "none",
    color: "var(--primary)",
    font: "inherit",
    textDecoration: "underline",
    cursor: "pointer",
    outline: "none",
  },
});
