import type { TexFlavor } from "@oleafly/backend-port";

export const RESEARCH_SEED_SENTINEL = "oleafly-real-research-seed-v1";

export type ResearchSeedKind = "document" | "image" | "diagram";
export type ResearchSeedEngine = "xetex" | "latexmk" | "typst" | "markdown";
export type ResearchSeedFigure =
  | "bibliography"
  | "cjk"
  | "diagram"
  | "equations"
  | "jpeg"
  | "pdf"
  | "plot"
  | "png"
  | "presentation"
  | "svg"
  | "table";

export interface ResearchSeedProject {
  name: string;
  repository: string;
  revision: string;
  license: string;
  kind: ResearchSeedKind;
  engine: ResearchSeedEngine;
  flavor?: TexFlavor;
  mainDoc: string;
  include: string[];
  figureTypes: ResearchSeedFigure[];
  shellEscape?: boolean;
  maxFiles?: number;
}

export const RESEARCH_SEED_PROJECTS: ResearchSeedProject[] = [
  {
    name: "IEEE Conference Paper (Typst)",
    repository: "typst/packages",
    revision: "01c8cd53646ff6d8e20c03008f992a8665bce839",
    license: "MIT-0",
    kind: "document",
    engine: "typst",
    mainDoc: "packages/preview/charged-ieee/0.1.4/template/main.typ",
    include: [
      "packages/preview/charged-ieee/0.1.4/lib.typ",
      "packages/preview/charged-ieee/0.1.4/template/main.typ",
      "packages/preview/charged-ieee/0.1.4/template/refs.bib",
    ],
    figureTypes: ["bibliography", "equations", "table"],
  },
  {
    name: "Fudan University Thesis (Typst)",
    repository: "fudan-kit/fudan-typst-thesis",
    revision: "3a92147c6ac53b096b50f989897a1241b51a0115",
    license: "GPL-3.0",
    kind: "document",
    engine: "typst",
    mainDoc: "main.typ",
    include: ["main.typ", "chapters/", "template/", "ref/", "figures/", "images/"],
    figureTypes: ["bibliography", "cjk", "diagram", "png"],
  },
  {
    name: "Poznan University Thesis (Typst)",
    repository: "RoyalDonkey/typst-put-thesis",
    revision: "3c1098d80c39ac40548843df4c4dbba2196b2fab",
    license: "MIT and MIT-0",
    kind: "document",
    engine: "typst",
    mainDoc: "template/thesis.typ",
    include: ["src/", "template/", "assets/"],
    figureTypes: ["bibliography", "plot", "svg"],
  },
  {
    name: "Peking University Thesis (Typst)",
    repository: "pku-typst/pkuthss-typst",
    revision: "41d60faa8c3134008a1e28b67a432dba5c3fae0c",
    license: "MIT",
    kind: "document",
    engine: "typst",
    mainDoc: "template/main.typ",
    include: ["template/", "lib/", "thesis.typ", "template.typ", "pkulogo.svg", "pkuword.svg"],
    figureTypes: ["bibliography", "cjk", "svg"],
  },
  {
    name: "Modern Academic CV (Typst)",
    repository: "ptsouchlos/modern-cv",
    revision: "f4e21240f030d7ecbeb656094e97abf8146b9299",
    license: "MIT",
    kind: "document",
    engine: "typst",
    mainDoc: "template/resume.typ",
    include: ["lib.typ", "template/"],
    figureTypes: ["jpeg", "png", "table"],
  },
  {
    name: "Touying Research Slides (Typst)",
    repository: "touying-typ/touying",
    revision: "3d5332b0d992bee8581df4c88e6e32bf7d23c143",
    license: "MIT",
    kind: "document",
    engine: "typst",
    mainDoc: "examples/example.typ",
    include: ["examples/example.typ", "lib.typ", "src/", "logo.png"],
    figureTypes: ["diagram", "png", "presentation"],
  },
  {
    name: "ACM Research Article (Typst)",
    repository: "fzaiser/faithful-acmart",
    revision: "7f36f942b0901b77908460a6fec0a21035a3c867",
    license: "MIT and MIT-0",
    kind: "document",
    engine: "typst",
    mainDoc: "template/main.typ",
    include: ["template/", "src/"],
    figureTypes: ["bibliography", "png", "svg", "table"],
    maxFiles: 220,
  },
  {
    name: "Digital Design Lab Report (Typst)",
    repository: "memset0/ZJU-Project-Report-Template",
    revision: "ed3bcafb9c81d42f07e40cbc23eae5a368b5e704",
    license: "MIT",
    kind: "document",
    engine: "typst",
    mainDoc: "examples/dd/report.typ",
    include: ["template.typ", "examples/dd/"],
    figureTypes: ["cjk", "diagram", "jpeg"],
  },
  {
    name: "TU Dresden Thesis (Typst)",
    repository: "typst-tud/tud-thesis",
    revision: "338c7cc22fa5a70d0bc34d244d2bf5aea435d819",
    license: "Apache-2.0",
    kind: "document",
    engine: "typst",
    mainDoc: "example/example.typ",
    include: ["example/", "logos/", "colors.typ", "tud-thesis.typ", "utils.typ"],
    figureTypes: ["bibliography", "svg", "table"],
  },
  {
    name: "Computer Science Thesis (Typst)",
    repository: "mrtz-j/typst-thesis-template",
    revision: "57de448c8f1ba8dd16db6ab3800af31c6d660fa5",
    license: "MIT",
    kind: "document",
    engine: "typst",
    mainDoc: "template/thesis.typ",
    include: ["lib.typ", "modules/", "assets/", "template/"],
    figureTypes: ["bibliography", "diagram", "jpeg", "plot", "png", "svg"],
  },
  {
    name: "AutoRA JOSS Paper (Markdown)",
    repository: "AutoResearch/autora-paper",
    revision: "0e29289dbf8625ed69b4fbdf2dac6960194b2594",
    license: "MIT",
    kind: "document",
    engine: "markdown",
    mainDoc: "paper.md",
    include: ["paper.md", "paper.bib", "figure.png", "figure.pdf"],
    figureTypes: ["bibliography", "pdf", "png"],
  },
  {
    name: "pvlib Python JOSS Paper (Markdown)",
    repository: "pvlib/pvlib-python",
    revision: "f02515571ab9d7cba2cab9af0c7e1c8155b10323",
    license: "BSD-3-Clause",
    kind: "document",
    engine: "markdown",
    mainDoc: "paper/paper.md",
    include: ["paper/paper.md", "paper/paper.bib", "paper/community.pdf", "paper/functions_06_010.pdf", "paper/timeline2.pdf"],
    figureTypes: ["bibliography", "pdf", "plot"],
  },
  {
    name: "mlpack JOSS Paper (Markdown)",
    repository: "mlpack/mlpack4_joss",
    revision: "17b34fefd6b95a2aa92a639269c712882588de1d",
    license: "Upstream repository license",
    kind: "document",
    engine: "markdown",
    mainDoc: "paper.md",
    include: ["paper.md", "paper.bib"],
    figureTypes: ["bibliography", "equations"],
  },
  {
    name: "LobsterPy JOSS Paper (Markdown)",
    repository: "JaGeo/LobsterPy",
    revision: "cb39f3a129ac1016beb6947c5b316de87a88d644",
    license: "BSD-3-Clause",
    kind: "document",
    engine: "markdown",
    mainDoc: "paper/paper.md",
    include: ["paper/"],
    figureTypes: ["bibliography", "plot", "png"],
    maxFiles: 100,
  },
  {
    name: "Rule-Based Integration JOSS Paper (Markdown)",
    repository: "RuleBasedIntegration/JOSS-Publication",
    revision: "339f219fd8f4091531623f848aa34cb8bc9fd22c",
    license: "MIT",
    kind: "document",
    engine: "markdown",
    mainDoc: "paper.md",
    include: ["paper.md", "paper.bib", "figure1.pdf"],
    figureTypes: ["bibliography", "equations", "pdf"],
  },
  {
    name: "Ethereum Yellow Paper",
    repository: "ethereum/yellowpaper",
    revision: "efc5f9a1f356cba376c978eedb63cb0363c2aa85",
    license: "CC-BY-SA-4.0",
    kind: "document",
    engine: "xetex",
    mainDoc: "Paper.tex",
    include: ["Paper.tex", "JS.tex", "Wire.tex", "Biblio.bib"],
    figureTypes: ["bibliography", "diagram", "equations", "table"],
  },
  {
    name: "OSMnx Street Networks Paper",
    repository: "gboeing/osmnx-paper",
    revision: "f89987278cb8fe9af9d6af82b17058039aaf9d86",
    license: "MIT",
    kind: "document",
    engine: "latexmk",
    flavor: "pdflatex",
    mainDoc: "osmnx-paper.tex",
    include: ["osmnx-paper.tex", "references.bib", "fig_graph_simplification.png", "fig_street_orientations.png", "fig_figure_ground.jpg"],
    figureTypes: ["bibliography", "diagram", "jpeg", "plot", "png"],
  },
  {
    name: "FPGA ResNet Systems Paper",
    repository: "ctuning/ck-request-asplos18-resnet-tvm-fpga",
    revision: "a163b6baf3272b95d7771368f962747cda4f71af",
    license: "CC-BY-4.0",
    kind: "document",
    engine: "latexmk",
    flavor: "pdflatex",
    mainDoc: "dissemination.publication/9375838469ad4029/paper.tex",
    include: ["dissemination.publication/9375838469ad4029/"],
    figureTypes: ["bibliography", "diagram", "pdf", "plot"],
    maxFiles: 120,
  },
  {
    name: "Scientific Visualization Book",
    repository: "rougier/scientific-visualization-book",
    revision: "62fa569f30333c817c13e4dc757877c1192fd15a",
    license: "CC-BY-NC-SA-4.0",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "tex/book.tex",
    include: [
      "tex/book.tex",
      "tex/book.bib",
      "tex/copyright.tex",
      "tex/front-cover.pdf",
      "figures/anatomy/raster-vector.pdf",
      "figures/colors/color-wheel.png",
      "figures/introduction/black-hole.jpg",
      "figures/showcases/windmap.png",
      "figures/threed/projection.svg",
    ],
    figureTypes: ["bibliography", "diagram", "jpeg", "plot", "png", "svg"],
    maxFiles: 180,
  },
  {
    name: "Category Theory for Programmers",
    repository: "hmemcpy/milewski-ctfp-pdf",
    revision: "01d9453871c59e08130136f936aaa0ca10de71cb",
    license: "CC-BY-SA-4.0",
    kind: "document",
    engine: "latexmk",
    flavor: "lualatex",
    mainDoc: "src/ctfp.tex",
    include: [
      "src/ctfp.tex",
      "src/preamble.tex",
      "src/category.tex",
      "src/content/1.1/category-the-essence-of-composition.tex",
      "src/content/1.1/images/",
      "src/fig/icons/",
    ],
    figureTypes: ["diagram", "equations", "png"],
    maxFiles: 140,
  },
  {
    name: "The Art of Linear Algebra",
    repository: "kenjihiranabe/The-Art-of-Linear-Algebra",
    revision: "0b1d5a5b55ebe29da26f6222764600ffedddae9f",
    license: "CC0-1.0",
    kind: "document",
    engine: "xetex",
    mainDoc: "The-Art-of-Linear-Algebra.tex",
    include: ["The-Art-of-Linear-Algebra.tex", "MatrixWorld.png", "MapofEigenvalues.png", "figs/"],
    figureTypes: ["diagram", "equations", "png"],
    maxFiles: 180,
  },
  {
    name: "Metropolis Research Presentation",
    repository: "matze/mtheme",
    revision: "2fa6084b9d34fec9d2d5470eb9a17d0bf712b6c8",
    license: "LPPL and GPL",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "demo/demo.tex",
    include: ["demo/", "source/"],
    figureTypes: ["bibliography", "pdf", "presentation"],
    maxFiles: 160,
  },
  {
    name: "Reproducible Preprint Template",
    repository: "gipplab/latexPaperTemplate",
    revision: "65aaf64bc379eadf33352a84fb8bf33e102f68cc",
    license: "Apache-2.0",
    kind: "document",
    engine: "xetex",
    mainDoc: "article_preprint.tex",
    include: ["article_preprint.tex", "01_title.tex", "02_abstract.tex", "03_mainmatter.tex", "short.bib"],
    figureTypes: ["bibliography", "table"],
  },
  {
    name: "Harvard Dissertation",
    repository: "suchow/Dissertate",
    revision: "2e92853c603cc9c8f56598dea26c5a0bce0f440b",
    license: "AGPL-3.0",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "assets/latex-base/dissertation.tex",
    include: ["assets/latex-base/"],
    figureTypes: ["bibliography", "pdf", "table"],
    maxFiles: 180,
  },
  {
    name: "Tsinghua University Thesis",
    repository: "tuna/thuthesis",
    revision: "fd3be474b1e66be85bcf286ea4be524b26c7e512",
    license: "LPPL-1.3c",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "thuthesis-example.tex",
    include: [
      "thuthesis-example.tex",
      "thusetup.tex",
      "data/",
      "ref/",
      "figures/",
      "thuthesis.dtx",
      "thuthesis.ins",
      "latexmkrc",
    ],
    figureTypes: ["bibliography", "cjk", "pdf", "table"],
    maxFiles: 200,
  },
  {
    name: "USTC Graduate Thesis",
    repository: "ustctug/ustcthesis",
    revision: "3b0d59ccd01cc9e0fbc09a97e3748fa3f4f2dddd",
    license: "LPPL-1.3c",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "main.tex",
    include: ["main.tex", "ustcthesis.cls", "ustcsetup.tex", "chapters/", "figures/", "references.bib"],
    figureTypes: ["bibliography", "cjk", "pdf", "table"],
    maxFiles: 180,
  },
  {
    name: "Awesome CV Research Resume",
    repository: "posquit0/Awesome-CV",
    revision: "8b850b477803a929a6dd74a74e3d5ab6b735d869",
    license: "LPPL-1.3c",
    kind: "document",
    engine: "latexmk",
    flavor: "xelatex",
    mainDoc: "examples/cv.tex",
    include: ["examples/cv.tex", "examples/cv/", "examples/profile.png", "awesome-cv.cls"],
    figureTypes: ["png", "table"],
  },
  {
    name: "University of Aveiro Thesis",
    repository: "ruiantunes/ua-thesis-template",
    revision: "58da041f0a317495b80abfc5f337bcd68e77b16e",
    license: "AGPL-3.0",
    kind: "document",
    engine: "latexmk",
    flavor: "lualatex",
    mainDoc: "main.tex",
    include: ["main.tex", "uathesis.sty", "refs.bib", "tex/", "img/logos/"],
    figureTypes: ["bibliography", "cjk", "pdf", "table"],
    maxFiles: 180,
  },
  {
    name: "XDP Networking Paper",
    repository: "tohojo/xdp-paper",
    revision: "672dc5ad9022229ead875c605e1ff030dee02bee",
    license: "CC-BY-SA",
    kind: "document",
    engine: "latexmk",
    flavor: "pdflatex",
    mainDoc: "xdp-paper.tex",
    include: ["xdp-paper.tex", "xdp.bib", "figures/"],
    figureTypes: ["bibliography", "diagram", "pdf", "svg"],
    shellEscape: true,
    maxFiles: 120,
  },
  {
    name: "PythonTeX Computational Gallery",
    repository: "gpoore/pythontex",
    revision: "78c98144145150b6884e3e68159fa8b95bc53c1d",
    license: "LPPL and BSD-3-Clause",
    kind: "document",
    engine: "latexmk",
    flavor: "pdflatex",
    mainDoc: "pythontex_gallery/pythontex_gallery.tex",
    include: ["pythontex_gallery/", "pythontex/"],
    figureTypes: ["plot", "png", "table"],
    shellEscape: true,
    maxFiles: 220,
  },
  {
    name: "Flash Attention Figure",
    repository: "opentikz/opentikz",
    revision: "359befbf8e8af7ce08e7e387b2c2a198e0ca735d",
    license: "CC0-1.0",
    kind: "image",
    engine: "xetex",
    mainDoc: "examples/flash-attention/figure.tex",
    include: ["examples/flash-attention/"],
    figureTypes: ["diagram"],
  },
  {
    name: "GAN Architecture Figure",
    repository: "opentikz/opentikz",
    revision: "359befbf8e8af7ce08e7e387b2c2a198e0ca735d",
    license: "CC0-1.0",
    kind: "image",
    engine: "xetex",
    mainDoc: "examples/gan/figure.tex",
    include: ["examples/gan/"],
    figureTypes: ["diagram"],
  },
  {
    name: "LoRA Matrix Diagram",
    repository: "opentikz/opentikz",
    revision: "359befbf8e8af7ce08e7e387b2c2a198e0ca735d",
    license: "CC0-1.0",
    kind: "image",
    engine: "xetex",
    mainDoc: "examples/lora/figure.tex",
    include: ["examples/lora/"],
    figureTypes: ["diagram"],
  },
  {
    name: "LoRA Diagram Composer Fixture",
    repository: "opentikz/opentikz",
    revision: "359befbf8e8af7ce08e7e387b2c2a198e0ca735d",
    license: "CC0-1.0",
    kind: "diagram",
    engine: "xetex",
    mainDoc: "examples/lora/figure.tex",
    include: ["examples/lora/"],
    figureTypes: ["diagram"],
  },
];
