/**
 * The declarative conversion registry: one source of truth for what Oleafly
 * can turn into what, which engine does the work, and where the feature
 * lives in the app. Three things are driven from this file:
 *
 *   1. the Import and Export menus (see src/components/layout and
 *      src/features/import-export),
 *   2. the pandoc route table the Rust backend executes (mirrored in
 *      src-tauri/src/conversion.rs and pinned together by tests on both
 *      sides),
 *   3. docs/conversion-matrix.md, regenerated by
 *      `pnpm gen:conversion-matrix`.
 *
 * Keep entries ordered by source format, then target. Every matrix cell is
 * either available, existing (shipped before the registry), or deferred with
 * a gap id and a one-line reason.
 */

export type TargetFormat =
  | "pdf"
  | "docx"
  | "html"
  | "markdown"
  | "latex"
  | "typst"
  | "bibtex"
  | "image";

export type SourceFormat =
  | "latex"
  | "markdown"
  | "typst"
  | "docx"
  | "html"
  | "pdf"
  | "image"
  | "csv"
  | "arxiv"
  | "doi"
  | "isbn"
  | "pmid"
  | "ris"
  | "endnote"
  | "zotero"
  | "bibtex";

export type ConversionEngine =
  | "pandoc"
  | "tectonic"
  | "typst"
  | "pdf-pipeline"
  | "api-lookup"
  | "internal";

export type RouteStatus = "available" | "existing" | "deferred";

export interface ConversionRoute {
  /** Stable id used by tests, docs links, and the backend mirror. */
  id: string;
  /** Short label for menus. */
  label: string;
  /** One sentence for the docs matrix. */
  blurb: string;
  source: SourceFormat;
  target: TargetFormat;
  /** import creates a project or library entry; export writes a file from an open project; tool runs on demand. */
  direction: "import" | "export" | "tool";
  engine: ConversionEngine;
  status: RouteStatus;
  /** Where the feature lives in the app. */
  surface: string;
  /** The gap this route closes (gap-analysis.md G-id), when it came from one. */
  gapId?: string;
  /** Required when status is "deferred". */
  deferredReason?: string;
  /** File extensions the Import dialog offers for import routes. */
  extensions?: string[];
  /** For pandoc routes: the reader and writer the backend uses. */
  pandoc?: { from: string; to: string; flags?: string[] };
}

export const REGISTRY: readonly ConversionRoute[] = [
  // --- LaTeX projects -----------------------------------------------------
  {
    id: "latex-to-pdf",
    label: "PDF",
    blurb: "Compile with the bundled Tectonic engine (or latexmk on a system TeX).",
    source: "latex",
    target: "pdf",
    direction: "export",
    engine: "tectonic",
    status: "existing",
    surface: "Export menu",
  },
  {
    id: "latex-to-docx",
    label: "Word (.docx)",
    blurb: "Pandoc writer with native OMML equations.",
    source: "latex",
    target: "docx",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    surface: "Export menu",
    pandoc: { from: "latex", to: "docx" },
  },
  {
    id: "latex-to-html",
    label: "HTML (MathML)",
    blurb: "Standalone self-contained HTML with MathML equations for accessibility.",
    source: "latex",
    target: "html",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    gapId: "G11",
    surface: "Export menu",
    pandoc: { from: "latex", to: "html5", flags: ["--standalone", "--embed-resources", "--mathml"] },
  },
  {
    id: "latex-to-markdown",
    label: "Markdown (.md)",
    blurb: "Pandoc writer; math lands in dollar delimiters.",
    source: "latex",
    target: "markdown",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    surface: "Export menu",
    pandoc: { from: "latex", to: "markdown" },
  },
  {
    id: "latex-to-typst",
    label: "Typst (.typ)",
    blurb: "Pandoc's typst writer with a fixup for its empty font declaration.",
    source: "latex",
    target: "typst",
    direction: "export",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Export menu",
    pandoc: { from: "latex", to: "typst", flags: ["--standalone"] },
  },
  {
    id: "latex-to-image",
    label: "Equation SVG / PNG",
    blurb: "Render a selected equation with MathJax and save it as SVG or PNG.",
    source: "latex",
    target: "image",
    direction: "tool",
    engine: "internal",
    status: "available",
    gapId: "G16",
    surface: "Editor context menu, Equation tool",
  },

  // --- Markdown -----------------------------------------------------------
  {
    id: "markdown-to-pdf",
    label: "PDF",
    blurb: "Pandoc compiles through the bundled Tectonic engine with citeproc.",
    source: "markdown",
    target: "pdf",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    surface: "Export menu",
  },
  {
    id: "markdown-to-docx",
    label: "Word (.docx)",
    blurb: "Pandoc writer.",
    source: "markdown",
    target: "docx",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    surface: "Export menu",
    pandoc: { from: "markdown", to: "docx" },
  },
  {
    id: "markdown-to-html",
    label: "HTML (MathML)",
    blurb: "Standalone self-contained HTML with MathML equations.",
    source: "markdown",
    target: "html",
    direction: "export",
    engine: "pandoc",
    status: "existing",
    surface: "Export menu",
    pandoc: { from: "markdown", to: "html5", flags: ["--standalone", "--embed-resources", "--mathml"] },
  },
  {
    id: "markdown-to-latex",
    label: "LaTeX (.tex)",
    blurb: "Import as a LaTeX project, or export .tex from a Markdown project.",
    source: "markdown",
    target: "latex",
    direction: "import",
    engine: "pandoc",
    status: "existing",
    surface: "Import dialog, Export menu",
    extensions: ["md", "markdown"],
    pandoc: { from: "markdown", to: "latex", flags: ["--standalone"] },
  },
  {
    id: "markdown-to-typst",
    label: "Typst (.typ)",
    blurb: "Import as a Typst project, or export .typ from a Markdown project.",
    source: "markdown",
    target: "typst",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog, Export menu",
    extensions: ["md", "markdown"],
    pandoc: { from: "markdown", to: "typst", flags: ["--standalone"] },
  },

  // --- Typst --------------------------------------------------------------
  {
    id: "typst-to-pdf",
    label: "PDF",
    blurb: "Compile with the bundled Typst engine.",
    source: "typst",
    target: "pdf",
    direction: "export",
    engine: "typst",
    status: "existing",
    surface: "Export menu",
  },
  {
    id: "typst-to-latex",
    label: "LaTeX (.tex)",
    blurb: "Import a Typst file as a LaTeX project, or export .tex from a Typst project.",
    source: "typst",
    target: "latex",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog, Export menu",
    extensions: ["typ"],
    pandoc: { from: "typst", to: "latex", flags: ["--standalone"] },
  },
  {
    id: "typst-to-markdown",
    label: "Markdown (.md)",
    blurb: "Pandoc's markdown writer; import as a Markdown project or export .md.",
    source: "typst",
    target: "markdown",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G28",
    surface: "Import dialog, Export menu",
    extensions: ["typ"],
    pandoc: { from: "typst", to: "markdown", flags: ["--standalone"] },
  },
  {
    id: "typst-to-html",
    label: "HTML (MathML)",
    blurb: "Standalone HTML export from a Typst project.",
    source: "typst",
    target: "html",
    direction: "export",
    engine: "pandoc",
    status: "available",
    gapId: "G28",
    surface: "Export menu",
    pandoc: { from: "typst", to: "html5", flags: ["--standalone", "--embed-resources", "--mathml"] },
  },
  {
    id: "typst-to-docx",
    label: "Word (.docx)",
    blurb: "Pandoc reads Typst directly and writes a .docx with OMML equations.",
    source: "typst",
    target: "docx",
    direction: "export",
    engine: "pandoc",
    status: "available",
    gapId: "G28",
    surface: "Export menu",
    pandoc: { from: "typst", to: "docx" },
  },

  // --- Word ---------------------------------------------------------------
  {
    id: "docx-to-latex",
    label: "LaTeX project",
    blurb: "Pandoc turns the document into a project, with OMML equations and media extracted to assets/.",
    source: "docx",
    target: "latex",
    direction: "import",
    engine: "pandoc",
    status: "existing",
    surface: "Import dialog",
    extensions: ["docx"],
    pandoc: { from: "docx", to: "latex", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "docx-to-markdown",
    label: "Markdown project",
    blurb: "Import as a Markdown project; export other formats from there.",
    source: "docx",
    target: "markdown",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
    extensions: ["docx"],
    pandoc: { from: "docx", to: "markdown", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "docx-to-typst",
    label: "Typst project",
    blurb: "Import as a Typst project.",
    source: "docx",
    target: "typst",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
    extensions: ["docx"],
    pandoc: { from: "docx", to: "typst", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "docx-to-pdf",
    label: "PDF",
    blurb: "Import as a LaTeX project, then compile.",
    source: "docx",
    target: "pdf",
    direction: "import",
    engine: "pandoc",
    status: "existing",
    surface: "Import dialog",
  },
  {
    id: "docx-to-html",
    label: "HTML (MathML)",
    blurb: "Import as a Markdown project, then export self-contained HTML with MathML.",
    source: "docx",
    target: "html",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog, then Export menu",
  },

  // --- HTML ---------------------------------------------------------------
  {
    id: "html-to-latex",
    label: "LaTeX project",
    blurb: "Pandoc's html reader; embedded images are extracted to assets/.",
    source: "html",
    target: "latex",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
    extensions: ["html", "htm"],
    pandoc: { from: "html", to: "latex", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "html-to-markdown",
    label: "Markdown project",
    blurb: "Import as a Markdown project.",
    source: "html",
    target: "markdown",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
    extensions: ["html", "htm"],
    pandoc: { from: "html", to: "markdown", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "html-to-typst",
    label: "Typst project",
    blurb: "Import as a Typst project.",
    source: "html",
    target: "typst",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
    extensions: ["html", "htm"],
    pandoc: { from: "html", to: "typst", flags: ["--standalone", "--extract-media=assets"] },
  },
  {
    id: "html-to-pdf",
    label: "PDF",
    blurb: "Import as a LaTeX project, then compile.",
    source: "html",
    target: "pdf",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog",
  },
  {
    id: "html-to-docx",
    label: "Word (.docx)",
    blurb: "Import as a LaTeX or Markdown project, then export Word.",
    source: "html",
    target: "docx",
    direction: "import",
    engine: "pandoc",
    status: "available",
    gapId: "G10",
    surface: "Import dialog, then Export menu",
  },

  // --- PDF ----------------------------------------------------------------
  {
    id: "pdf-to-latex",
    label: "LaTeX project",
    blurb: "The built-in text-layer pipeline: columns, headings, math detection, and figure extraction.",
    source: "pdf",
    target: "latex",
    direction: "import",
    engine: "pdf-pipeline",
    status: "existing",
    surface: "Import dialog",
  },
  {
    id: "pdf-to-image",
    label: "Page PNG",
    blurb: "Render any page of the compiled PDF to a PNG at 3x.",
    source: "pdf",
    target: "image",
    direction: "export",
    engine: "pdf-pipeline",
    status: "available",
    surface: "Export menu",
  },
  {
    id: "pdf-to-docx",
    label: "Word (.docx)",
    blurb: "Not built yet.",
    source: "pdf",
    target: "docx",
    direction: "import",
    engine: "pdf-pipeline",
    status: "deferred",
    gapId: "G13",
    deferredReason: "PDF ingestion quality (G13) needs the layout-model stage before Word output is worth shipping; today it goes PDF to LaTeX to .docx.",
    surface: "Import dialog",
  },
  {
    id: "pdf-to-html",
    label: "HTML",
    blurb: "Not built yet.",
    source: "pdf",
    target: "html",
    direction: "import",
    engine: "pdf-pipeline",
    status: "deferred",
    gapId: "G13",
    deferredReason: "Same quality gate as PDF to Word; the LaTeX path exists today.",
    surface: "Import dialog",
  },
  {
    id: "pdf-to-markdown",
    label: "Markdown",
    blurb: "Not built yet.",
    source: "pdf",
    target: "markdown",
    direction: "import",
    engine: "pdf-pipeline",
    status: "deferred",
    gapId: "G13",
    deferredReason: "Same quality gate as PDF to Word; the LaTeX path exists today.",
    surface: "Import dialog",
  },
  {
    id: "pdf-scanned-to-latex",
    label: "Scanned PDF to LaTeX",
    blurb: "Scanned pages stop at a clear no-text-layer message.",
    source: "pdf",
    target: "latex",
    direction: "import",
    engine: "pdf-pipeline",
    status: "deferred",
    gapId: "G2",
    deferredReason: "OCR for scanned PDFs is not in yet; the importer reports which pages have no text layer.",
    surface: "Import dialog",
  },

  // --- Images -------------------------------------------------------------
  {
    id: "image-to-latex",
    label: "LaTeX equation",
    blurb: "A vision model transcribes an equation or table photo to LaTeX at the cursor.",
    source: "image",
    target: "latex",
    direction: "tool",
    engine: "internal",
    status: "existing",
    surface: "Editor toolbar",
  },

  // --- Spreadsheets -------------------------------------------------------
  {
    id: "csv-to-latex",
    label: "LaTeX booktabs table",
    blurb: "Parse CSV (or XLSX via SheetJS) and emit a booktabs table with full escaping, insertable at the cursor.",
    source: "csv",
    target: "latex",
    direction: "tool",
    engine: "internal",
    status: "available",
    gapId: "G17",
    surface: "Editor context menu, Table tool",
    extensions: ["csv", "tsv", "xlsx", "xls"],
  },
  {
    id: "csv-to-typst",
    label: "Typst table",
    blurb: "Same parser, Typst table emitter.",
    source: "csv",
    target: "typst",
    direction: "tool",
    engine: "internal",
    status: "available",
    gapId: "G17",
    surface: "Editor context menu, Table tool",
    extensions: ["csv", "tsv", "xlsx", "xls"],
  },

  // --- arXiv --------------------------------------------------------------
  {
    id: "arxiv-to-latex",
    label: "LaTeX project",
    blurb: "Download the e-print tarball, unpack it, and infer the main document.",
    source: "arxiv",
    target: "latex",
    direction: "import",
    engine: "api-lookup",
    status: "available",
    gapId: "G7",
    surface: "Import dialog",
  },
  {
    id: "arxiv-to-bibtex",
    label: "BibTeX",
    blurb: "The arXiv Atom entry becomes a citation.",
    source: "arxiv",
    target: "bibtex",
    direction: "tool",
    engine: "api-lookup",
    status: "existing",
    surface: "Add citation dialog",
  },

  // --- Identifiers --------------------------------------------------------
  {
    id: "doi-to-bibtex",
    label: "BibTeX",
    blurb: "doi.org content negotiation.",
    source: "doi",
    target: "bibtex",
    direction: "tool",
    engine: "api-lookup",
    status: "existing",
    surface: "Add citation dialog",
  },
  {
    id: "isbn-to-bibtex",
    label: "BibTeX",
    blurb: "OpenLibrary lookup for books.",
    source: "isbn",
    target: "bibtex",
    direction: "tool",
    engine: "api-lookup",
    status: "available",
    gapId: "G7",
    surface: "Add citation dialog",
  },
  {
    id: "pmid-to-bibtex",
    label: "BibTeX",
    blurb: "NCBI E-utilities lookup for PubMed articles.",
    source: "pmid",
    target: "bibtex",
    direction: "tool",
    engine: "api-lookup",
    status: "available",
    gapId: "G7",
    surface: "Add citation dialog",
  },

  // --- Reference-manager exports -----------------------------------------
  {
    id: "ris-to-bibtex",
    label: "BibTeX",
    blurb: "RIS export files import into the reference library.",
    source: "ris",
    target: "bibtex",
    direction: "import",
    engine: "internal",
    status: "existing",
    surface: "References panel",
  },
  {
    id: "endnote-to-bibtex",
    label: "BibTeX",
    blurb: "EndNote XML export files import into the reference library.",
    source: "endnote",
    target: "bibtex",
    direction: "import",
    engine: "internal",
    status: "existing",
    surface: "References panel",
  },
  {
    id: "zotero-to-bibtex",
    label: "BibTeX",
    blurb: "Zotero RDF export files import into the reference library.",
    source: "zotero",
    target: "bibtex",
    direction: "import",
    engine: "internal",
    status: "existing",
    surface: "References panel",
  },

  // --- BibTeX library -----------------------------------------------------
  {
    id: "bibtex-clean",
    label: "Cleaned library",
    blurb: "Normalize keys, drop DOI and fuzzy-title duplicates, and report missing fields with a dry-run diff.",
    source: "bibtex",
    target: "bibtex",
    direction: "tool",
    engine: "internal",
    status: "available",
    gapId: "G6",
    surface: "References panel, BibTeX tool",
  },
];

/** Routes that create new projects, in menu order. */
export function importRoutes(): readonly ConversionRoute[] {
  return REGISTRY.filter(
    (route) =>
      route.direction === "import" &&
      route.status !== "deferred" &&
      route.extensions !== undefined,
  );
}

/** Find the import route matching a picked file extension and chosen target. */
export function importRouteFor(
  extension: string,
  target: string,
): ConversionRoute | undefined {
  return REGISTRY.find(
    (route) =>
      route.direction === "import" &&
      route.status !== "deferred" &&
      route.extensions?.includes(extension) &&
      targetForRoute(route) === target,
  );
}

function targetForRoute(route: ConversionRoute): string | undefined {
  switch (route.target) {
    case "latex":
      return "latex";
    case "markdown":
      return "markdown";
    case "typst":
      return "typst";
    default:
      return undefined;
  }
}

/** Export formats an engine can write, in menu order. */
export function exportRoutesFor(
  engineId: string,
  exports: readonly string[],
): readonly ConversionRoute[] {
  const sourcesByEngine: Record<string, SourceFormat[]> = {
    latex: ["latex"],
    latexmk: ["latex"],
    typst: ["typst"],
    markdown: ["markdown"],
  };
  const sources = sourcesByEngine[engineId];
  if (!sources) {
    return [];
  }
  // Menu order per engine; "tex"/"md" are the backend's export format ids
  // for LaTeX/Markdown targets.
  const order: Record<string, string[]> = {
    latex: ["pdf", "docx", "html", "md", "typst", "txt", "pptx", "epub"],
    latexmk: ["pdf", "docx", "html", "md", "typst", "txt", "pptx", "epub"],
    typst: ["pdf", "tex", "docx", "html", "md", "txt"],
    markdown: ["pdf", "docx", "html", "typst", "tex", "txt", "pptx", "epub"],
  };
  const targetForFormat: Record<string, TargetFormat> = {
    pdf: "pdf",
    docx: "docx",
    html: "html",
    md: "markdown",
    typst: "typst",
    tex: "latex",
  };
  const routes: ConversionRoute[] = [];
  for (const format of order[engineId] ?? []) {
    if (!exports.includes(format)) {
      continue;
    }
    const target = targetForFormat[format];
    // Bidirectional routes (import a file, or export from that engine's
    // project) qualify through their source, whichever menu they list first.
    const route = REGISTRY.find(
      (candidate) =>
        candidate.direction !== "tool" &&
        candidate.status !== "deferred" &&
        sources.includes(candidate.source) &&
        candidate.target === target,
    );
    if (route && !routes.some((existing) => existing.id === route.id)) {
      routes.push(route);
    }
  }
  return routes;
}

/** Every deferred route, for docs and planning. */
export function deferredRoutes(): readonly ConversionRoute[] {
  return REGISTRY.filter((route) => route.status === "deferred");
}
