#import "../lib/style.typ": *

= Contact-Consistent Grasp Planning <sec:planning>

== Architecture

Palisade is organised as three concurrent loops running at different rates,
shown in @fig:architecture. The vision loop runs once per grasp attempt and
produces a set of candidate approach poses from a single depth image. The
tactile loop runs at 180 Hz and maintains the contact state described in
@sec:patch. The revision loop runs at 60 Hz during closure, rescores the
surviving candidates against the current contact state, and either confirms the
active candidate, commands a lateral correction, or requests a fresh approach.

The separation is deliberate. Rescoring every candidate at the tactile rate
would be wasteful, since the contact state changes slowly relative to the taxel
scan, and it would couple the planner to sensor noise. Rescoring only once, at
first contact, would miss the redistribution that occurs as normal force
builds, which is exactly the phase in which a deformable object reveals its
behaviour.

#figure(
  box(width: 13.0cm, height: 7.05cm, {
    node(0.0cm, 0.60cm, 2.9cm, 1.05cm, [Depth camera], size: 8pt)
    node(0.0cm, 2.55cm, 2.9cm, 1.30cm, [Candidate generator\ #text(size: 7pt)[antipodal sampling]], size: 8pt)
    node(0.0cm, 4.50cm, 2.9cm, 1.05cm, [TX-40 arrays\ #text(size: 7pt)[two fingers, 180 Hz]], size: 8pt)

    node(4.5cm, 0.60cm, 3.4cm, 1.05cm, [Approach controller], size: 8pt)
    node(4.5cm, 2.55cm, 3.4cm, 1.30cm, [Revision loop, 60 Hz\ #text(size: 7pt)[rescore, correct, abort]], fill: luma(95%), size: 8pt)
    node(4.5cm, 4.50cm, 3.4cm, 1.05cm, [Contact state estimator\ #text(size: 7pt)[patch, shear, friction]], size: 8pt)

    node(9.5cm, 0.60cm, 3.5cm, 1.05cm, [Arm servo, 1 kHz], size: 8pt)
    node(9.5cm, 2.55cm, 3.5cm, 1.30cm, [Quality metric\ #text(size: 7pt)[patch-conditioned wrench hull]], size: 8pt)
    node(9.5cm, 4.50cm, 3.5cm, 1.05cm, [Slip predictor\ #text(size: 7pt)[shear divergence]], size: 8pt)

    node(4.5cm, 6.15cm, 8.5cm, 0.80cm, [Grip force regulator and regrasp policy], fill: luma(93%), size: 8pt)

    harrow(2.9cm, 1.125cm, 1.6cm)
    harrow(2.9cm, 3.200cm, 1.6cm)
    harrow(2.9cm, 5.025cm, 1.6cm)
    harrow(7.9cm, 1.125cm, 1.6cm)
    harrow(7.9cm, 3.200cm, 1.6cm)
    harrow(7.9cm, 5.025cm, 1.6cm)

    varrow(1.45cm, 1.65cm, 0.90cm)
    varrow(6.20cm, 4.50cm, -0.65cm, color: accent)
    varrow(11.25cm, 5.55cm, 0.60cm, color: accent2)
    seg(4.50cm, 3.55cm, 4.15cm, 3.55cm, dash: "dashed")
    seg(4.15cm, 3.55cm, 4.15cm, 6.55cm, dash: "dashed")
    harrow(4.15cm, 6.55cm, 0.35cm, dash: "dashed")

    lbl(2.9cm, 0.79cm, [point cloud], w: 1.6cm, size: 6.5pt)
    lbl(2.9cm, 2.86cm, [candidates], w: 1.6cm, size: 6.5pt)
    lbl(2.9cm, 4.69cm, [taxel frames], w: 1.6cm, size: 6.5pt)
    lbl(7.9cm, 0.79cm, [pose command], w: 1.6cm, size: 6.5pt)
    lbl(7.9cm, 2.86cm, [ranked set], w: 1.6cm, size: 6.5pt)
    lbl(7.9cm, 4.69cm, [shear field], w: 1.6cm, size: 6.5pt)
    lbl(6.35cm, 3.92cm, [patch and $hat(mu)$], w: 2.2cm, size: 6.5pt, al: left)
    lbl(11.40cm, 5.65cm, [slip flag], w: 1.6cm, size: 6.5pt, al: left)
    lbl(2.30cm, 6.20cm, [regrasp decision], w: 1.8cm, size: 6.5pt, al: right)
  }),
  caption: [
    Palisade architecture. Solid arrows carry data and the dashed arrow carries
    a control decision from the revision loop to the force regulator. Tactile
    evidence reaches both the quality metric and the force regulator, and the
    path from the contact state estimator into the revision loop is the one
    that prior reactive systems do not have.
  ],
) <fig:architecture>

== Candidate generation

Candidates are generated by the standard antipodal procedure. The depth image
is converted to a point cloud, surface normals are estimated over a 6 mm
neighbourhood, and pairs of points whose normals are within 22 degrees of
antiparallel and whose separation lies inside the gripper stroke are retained.
Each pair defines a grasp axis, and a rotation about that axis is sampled at 15
degree increments. Kinematic reachability and a collision check against the
scene mesh prune the set. A typical bin scene yields between 300 and 1800
surviving candidates. This part of the pipeline follows established practice
@tenpas2017grasp and is not a contribution of this thesis.

== A patch-conditioned quality metric <sec:metric>

The classical measure of @eq:qfc assumes a point contact. We replace it with a
measure over the observed patch. The construction proceeds in three steps.

*Step one: discretise the patch.* Partition $Omega$ into $q$ cells of roughly
equal normal force, using a k-means split on the taxel coordinates weighted by
pressure. Each cell $k$ contributes a sub-contact at its own centroid $x_k$
with normal force $F_k$ and local surface normal $n_k$ recovered from the
gradient of the pressure field. In practice $q = 5$ is sufficient: raising it
to 9 changes the resulting quality by less than 1.5 percent while tripling the
hull computation time.

*Step two: aperture per cell.* The friction cone aperture of cell $k$ is not
the global $hat(mu)$ but a value reduced by the fraction of the cell already in
partial slip. Let $sigma_k in [0, 1]$ be the stuck fraction of cell $k$,
estimated from the shear field as described in @sec:slip. We set

$ mu_k = hat(mu) sigma_k^(1 / 2). $ <eq:mu-cell>

The square root is empirical. A linear reduction proved too aggressive, in the
sense that it drove the planner to reject grasps that in fact held, and no
reduction at all left the metric blind to the boundary annulus.

*Step three: hull and radius.* Each cell contributes $m = 8$ generator wrenches
built from its own cone. The patch-conditioned quality is

$ Q_"pc" = min_(w in partial "conv"(cal(W)_"pc")) norm(w), quad
  cal(W)_"pc" = union.big_(k=1)^q { vec(g_(k,j), (x_k - p) times g_(k,j)) }_(j=1)^m. $ <eq:qpc>

#proposition("reduction to the classical measure")[
  If the patch degenerates to a single cell at $x_1$ with $sigma_1 = 1$, then
  $cal(W)_"pc"$ coincides with the primitive wrench set of @eq:wrenchset and
  $Q_"pc" = Q_"FC"$.
]

The reduction matters because it makes the comparison with a point-contact
planner a comparison of contact models rather than of metrics. Any difference
in behaviour must come from the patch, not from a different notion of quality.

== Deformation penalty

A grasp that is excellent in wrench space may still be unacceptable because it
crushes the object. We add a penalty term driven by the observed compliance.
During closure the estimator records the relation between commanded finger
displacement $delta$ and measured total normal force $F$. For a locally linear
material this relation has slope $k_"obj"$, and the penalty

$ Pi(F) = cases(
  0 & "if" F <= F_"safe",
  rho (F - F_"safe")^2 & "otherwise"
), quad F_"safe" = F_"req" + 2 sqrt(k_"obj") / rho, $ <eq:penalty>

discourages force beyond what the task requires. $F_"req"$ is the normal force
needed to resist the transport wrench at the current $hat(mu)$, and $rho$ is
set so that the penalty equals the typical spread of $Q_"pc"$ at twice
$F_"safe"$. The planner maximises $Q_"pc" - Pi(F)$.

@fig:cone shows the geometric consequence of the patch conditioning. The single
wide cone that a point-contact planner assumes is replaced by five narrower
cones whose apertures differ, and the boundary cells, whose stuck fraction has
already fallen, contribute least.

#figure(
  box(width: 11.6cm, height: 5.4cm, {
    place(dx: 0.6cm, dy: 0.4cm, box(width: 4.2cm, height: 4.4cm, {
      seg(0cm, 3.6cm, 4.0cm, 3.6cm, thickness: 0.9pt)
      place(dx: 1.15cm, dy: 3.55cm, rect(width: 1.7cm, height: 0.1cm, fill: luma(60%), stroke: none))
      place(dx: 2.0cm, dy: 0.55cm, polygon(
        fill: rgb(31, 78, 121, 40),
        stroke: 0.7pt + accent,
        (0cm, 3.0cm),
        (-1.35cm, 0cm),
        (1.35cm, 0cm),
      ))
      varrow(2.0cm, 1.0cm, 2.4cm, color: accent2)
      lbl(2.1cm, 1.5cm, text(fill: accent2)[$f$], w: 1cm, al: left)
      lbl(0.0cm, 4.05cm, [point contact, aperture $arctan hat(mu)$], w: 4.0cm)
    }))

    place(dx: 6.0cm, dy: 0.4cm, box(width: 5.0cm, height: 4.4cm, {
      seg(0cm, 3.6cm, 4.8cm, 3.6cm, thickness: 0.9pt)
      place(dx: 0.5cm, dy: 3.55cm, rect(width: 3.8cm, height: 0.1cm, fill: luma(60%), stroke: none))
      let cells = ((0.75cm, 0.26), (1.55cm, 0.62), (2.40cm, 0.86), (3.20cm, 0.62), (4.00cm, 0.26))
      for c in cells {
        let x = c.at(0)
        let s = c.at(1)
        let half = 0.30cm + 0.62cm * s
        let hgt = 1.1cm + 1.5cm * s
        place(dx: x, dy: 3.55cm - hgt, polygon(
          fill: rgb(31, 78, 121, 34),
          stroke: 0.55pt + accent,
          (0cm, hgt),
          (-half, 0cm),
          (half, 0cm),
        ))
        place(dx: x - 1.2pt, dy: 3.5cm, circle(radius: 1.2pt, fill: black, stroke: none))
      }
      lbl(0.0cm, 4.05cm, [patch contact, aperture $arctan mu_k$ per cell], w: 4.8cm)
    }))

    lbl(4.6cm, 2.2cm, [$arrow.r$], w: 1.4cm, size: 12pt)
  }),
  caption: [
    Contact model comparison. On the left, the point-contact model concentrates
    the entire friction budget at one location with a single aperture. On the
    right, the patch model distributes it over five cells whose apertures are
    reduced by their measured stuck fraction, so the boundary cells contribute
    the least.
  ],
) <fig:cone>

== Optimisation during closure

The revision loop cannot afford to rescore 1800 candidates at 60 Hz. It
maintains an active set of the 24 highest-scoring candidates from the vision
stage and rescores only those, using the patch observed for the active
candidate to predict the patch that each alternative would produce. The
prediction is a rigid transport of the observed patch to the alternative
contact location, corrected for the local surface curvature estimated from the
point cloud. It is crude, and it is only used for ranking, not for the final
decision.

The listing below is the inner loop as it runs on the host, with the wrench
hull computed incrementally.

```c
static float rescore_active_set(const patch_t *observed,
                                candidate_t *cands, int n,
                                float mu_hat, float f_req)
{
    float best = -1.0f;
    for (int i = 0; i < n; ++i) {
        patch_t predicted;
        transport_patch(observed, &cands[i].pose, &predicted);
        if (predicted.area_taxels < MIN_PATCH_TAXELS) {
            cands[i].quality = 0.0f;
            continue;
        }
        cell_t cells[Q_CELLS];
        split_patch(&predicted, cells, Q_CELLS);
        for (int k = 0; k < Q_CELLS; ++k)
            cells[k].mu = mu_hat * sqrtf(cells[k].stuck_fraction);

        float q = hull_radius(cells, Q_CELLS, &cands[i].pose);
        float excess = cands[i].force - safe_force(f_req, cands[i].k_obj);
        if (excess > 0.0f)
            q -= RHO * excess * excess;

        cands[i].quality = q;
        if (q > best) best = q;
    }
    return best;
}
```

Two implementation details carry more weight than they appear to. The early
rejection on `MIN_PATCH_TAXELS` removes line contacts before the hull is
computed and accounts for roughly forty percent of the loop's time saving. The
incremental hull, which reuses the facet structure from the previous frame when
the cell centroids have moved by less than one taxel, brings the worst-case
loop time from 21.4 ms down to 9.8 ms, which is what makes 60 Hz attainable.

== Decision rule

At each revision step the loop compares the quality of the active candidate,
$Q_a$, against the best alternative, $Q_b$, and applies the following rule. If
$Q_a >= 0.8 Q_b$, keep the active candidate. If $Q_a < 0.8 Q_b$ and the
required correction is a translation of less than 8 mm along the object
surface, command the correction and continue closing. Otherwise open the
gripper, retract 40 mm, and re-approach on the best alternative.

The 8 mm threshold is the distance beyond which sliding the fingers on a
deformable surface begins to bunch the material ahead of the contact, which
changes the geometry the correction was computed for. We measured the onset by
sliding a loaded finger across the six deformable objects in the test set and
recording the displacement at which the measured patch area grew by more than
fifteen percent.
