export const TOUR_IDS = ["home", "workspace", "settings", "ai-settings", "ai", "diagram"] as const;

export type TourId = (typeof TOUR_IDS)[number];
export type TourStatus = "pending" | "completed" | "dismissed";
export type TourContext = "home" | "project" | "settings" | "ai" | "diagram";
export type TourStepKind = "informational" | "required-click" | "required-input" | "transition";

export interface TourStepDefinition {
  id: string;
  target: `[data-tour="${string}"]`;
  interactionTarget?: `[data-tour="${string}"]`;
  interactionArea?: `[data-tour="${string}"]`;
  spotlightTarget?: `[data-tour="${string}"]`;
  kind: TourStepKind;
  title: string;
  content: string;
  waitForTarget?: boolean;
  placement?: "center" | "auto" | "top" | "bottom" | "left" | "right" | "bottom-end";
}

export interface TourDefinition {
  id: TourId;
  label: string;
  version: number;
  contexts: readonly TourContext[];
  priority: number;
  steps: readonly TourStepDefinition[];
}

export const tourRegistry = {
  home: {
    id: "home",
    label: "Getting started",
    version: 4,
    contexts: ["home"],
    priority: 10,
    steps: [
      {
        id: "home-overview",
        target: '[data-tour="home"]',
        kind: "informational",
        title: "Home",
        content: "Your projects and project creation begin here.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "home-create",
        target: '[data-tour="new-project"]',
        kind: "required-click",
        title: "Create a real project",
        content: "Choose New project to open the template gallery.",
        waitForTarget: true,
        placement: "bottom-end",
      },
      {
        id: "home-gallery",
        target: '[data-tour="project-template-gallery"]',
        kind: "informational",
        title: "Find your starting point",
        content: "Browse categories, search by name, and narrow templates by compiler or offline availability.",
        waitForTarget: true,
        // The target is the whole near-fullscreen dialog, so a fixed side
        // clips on smaller windows; "auto" picks whichever edge has room
        // and always renders outside the dialog instead of on top of it.
        placement: "auto",
      },
      {
        id: "home-template",
        target: '[data-tour="project-template-gallery"]',
        interactionTarget: '[data-tour="project-template-card"]',
        interactionArea: '[data-tour="project-template-gallery"]',
        kind: "required-click",
        title: "Choose a template",
        content: "Select any real template to continue. Its files will become your new project.",
        waitForTarget: true,
        // Same large target as home-gallery: "center" rendered the tooltip
        // directly over the template grid, blocking clicks on the cards
        // underneath it. "auto" keeps it outside the dialog's bounds.
        placement: "auto",
      },
      {
        id: "home-name",
        target: '[data-tour="project-name"]',
        kind: "required-input",
        title: "Name your project",
        content: "Enter a project name. Next becomes available when the name is not empty.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "home-color",
        target: '[data-tour="project-cover-color"]',
        interactionArea: '[data-tour="project-cover-color"]',
        kind: "informational",
        title: "Choose a cover color",
        content: "This color makes the project easy to spot on Home. You can keep the template default.",
        waitForTarget: true,
        placement: "top",
      },
      {
        id: "home-create-project",
        target: '[data-tour="create-project"]',
        kind: "required-click",
        title: "Create your project",
        content: 'Click "Create project" to create a project with the selected template.',
        waitForTarget: true,
        placement: "top",
      },
    ],
  },
  workspace: {
    id: "workspace",
    label: "Your workspace",
    version: 4,
    contexts: ["project"],
    priority: 20,
    steps: [
      {
        id: "workspace-toolbar",
        target: '[data-tour="project-toolbar"]',
        kind: "informational",
        title: "Project toolbar",
        content: "Project actions and compilation controls live here.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-sidebar",
        target: '[data-tour="project-sidebar"]',
        kind: "informational",
        title: "Workspace navigation",
        content: "Move between files, search, source control, preflight, AI, integrations, and project tools.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "workspace-editor",
        target: '[data-tour="project-editor"]',
        kind: "informational",
        title: "Editor",
        content: "Write and navigate source with completion, diagnostics, formatting, and code intelligence.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "workspace-wysiwyg-toggle",
        target: '[data-tour="wysiwyg-toggle"]',
        kind: "informational",
        title: "Try WYSIWYG mode",
        content: "Switch between raw source and a formatted, Google-Docs-style view of your document.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-compile",
        target: '[data-tour="project-compile"]',
        kind: "informational",
        title: "Compile and recompile",
        content: "Build the current project here. The tour never compiles or changes your source.",
        waitForTarget: true,
        placement: "bottom-end",
      },
      {
        id: "workspace-logs",
        target: '[data-tour="project-compile-logs"]',
        kind: "informational",
        title: "Build logs",
        content: "Open build logs to inspect errors without changing project content. The adjacent status shows the latest compile time.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-preview",
        target: '[data-tour="project-preview"]',
        kind: "informational",
        title: "PDF preview",
        content: "The compiled document stays beside your source in split view.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "workspace-zoom",
        target: '[data-tour="project-preview-zoom"]',
        kind: "informational",
        title: "Preview controls",
        content: "Adjust zoom, search the document, and export the PDF from the preview toolbar.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-source-navigation",
        target: '[data-tour="project-preview-content"]',
        kind: "informational",
        title: "PDF to source",
        content: "Click compiled PDF content to jump directly to the corresponding source.",
        waitForTarget: true,
        placement: "left",
      },
    ],
  },
  settings: {
    id: "settings",
    label: "Settings",
    version: 2,
    contexts: ["settings"],
    priority: 30,
    steps: [
      {
        id: "settings-navigation",
        target: '[data-tour="settings-navigation"]',
        spotlightTarget: '[data-tour="settings-navigation-panel"]',
        kind: "informational",
        title: "Settings",
        content: "Move between preferences and integrations here.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "settings-general",
        target: '[data-tour="settings-general"]',
        spotlightTarget: '[data-tour="settings-general-panel"]',
        kind: "transition",
        title: "General preferences",
        content: "Control editing behavior, offline mode, shortcuts, and tour guides.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-appearance",
        target: '[data-tour="settings-appearance"]',
        spotlightTarget: '[data-tour="settings-appearance-panel"]',
        kind: "transition",
        title: "Appearance",
        content: "Choose the theme, typography, default workspace layout, and accent color.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-dictionary",
        target: '[data-tour="settings-dictionary"]',
        spotlightTarget: '[data-tour="settings-dictionary-panel"]',
        kind: "transition",
        title: "Dictionary",
        content: "Review project-specific and global words ignored by spelling and grammar checks.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-data",
        target: '[data-tour="settings-data"]',
        spotlightTarget: '[data-tour="settings-data-panel"]',
        kind: "transition",
        title: "Data Storage",
        content: "Inspect local project storage and manage application data.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-ai",
        target: '[data-tour="settings-ai"]',
        spotlightTarget: '[data-tour="settings-ai-panel"]',
        kind: "transition",
        title: "AI Assistant",
        content: "Configure providers, models, and credentials for the project assistant.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-compiler",
        target: '[data-tour="settings-compiler"]',
        spotlightTarget: '[data-tour="settings-compiler-panel"]',
        kind: "transition",
        title: "Compiler",
        content: "Choose and configure the LaTeX engine used to build projects.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-downloads",
        target: '[data-tour="settings-downloads"]',
        spotlightTarget: '[data-tour="settings-downloads-panel"]',
        kind: "transition",
        title: "Downloads",
        content: "Manage packages and resources available for offline work.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-integrations",
        target: '[data-tour="settings-integrations"]',
        spotlightTarget: '[data-tour="settings-integrations-panel"]',
        kind: "transition",
        title: "Integrations",
        content: "Connect GitHub, alphaXiv, Zotero, and other services Oleafly integrates with.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-shortcuts",
        target: '[data-tour="settings-shortcuts"]',
        spotlightTarget: '[data-tour="settings-shortcuts-panel"]',
        kind: "transition",
        title: "Keyboard Shortcuts",
        content: "Review, edit, set, and reset application keyboard shortcuts.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-mcp",
        target: '[data-tour="settings-mcp"]',
        spotlightTarget: '[data-tour="settings-mcp-panel"]',
        kind: "transition",
        title: "MCP",
        content: "Manage Model Context Protocol connections and available integrations.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-help",
        target: '[data-tour="settings-help"]',
        spotlightTarget: '[data-tour="settings-help-panel"]',
        kind: "transition",
        title: "Help and About",
        content: "Restart the contextual tour, open documentation, view shortcuts, or report a problem.",
        waitForTarget: true,
        placement: "left",
      },
    ],
  },
  "ai-settings": {
    id: "ai-settings",
    label: "AI settings",
    version: 1,
    contexts: ["settings"],
    priority: 35,
    steps: [
      {
        id: "ai-settings-tabs",
        target: '[data-tour="ai-settings-tabs"]',
        kind: "informational",
        title: "AI Assistant settings",
        content: "Providers and keys, Instructions, and Personas. Everything the assistant does starts here.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-providers",
        target: '[data-tour="ai-settings-providers"]',
        kind: "informational",
        title: "Connect providers",
        content: "Paste a key and it is validated against the provider before saving. Connected providers show a green badge and expand into a model list you can toggle, extend, or restore. Keys stay encrypted on this computer.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-custom-provider",
        target: '[data-tour="ai-settings-custom-provider"]',
        kind: "informational",
        title: "Bring your own endpoint",
        content: "Any OpenAI-compatible base URL works here, including local servers like Ollama or LM Studio.",
        waitForTarget: true,
        placement: "top",
      },
      {
        id: "ai-settings-open-instructions",
        target: '[data-tour="ai-settings-tab-instructions"]',
        kind: "required-click",
        title: "Instructions",
        content: "Click the Instructions tab to continue.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-default-model",
        target: '[data-tour="ai-default-model"]',
        kind: "informational",
        title: "Default model",
        content: "New chats start with this model. You can still switch models per conversation from the chat panel.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-instructions",
        target: '[data-tour="ai-instructions"]',
        kind: "informational",
        title: "Custom instructions",
        content: "Your standing style preferences, added to every request the assistant makes.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-open-personas",
        target: '[data-tour="ai-settings-tab-personas"]',
        kind: "required-click",
        title: "Personas",
        content: "Click the Personas tab to continue.",
        waitForTarget: true,
      },
      {
        id: "ai-settings-personas",
        target: '[data-tour="ai-create-persona"]',
        kind: "informational",
        title: "Create personas",
        content: "Named instruction sets with a color, switchable from the chat's Persona menu. Try a copyeditor, a reviewer, or a LaTeX purist.",
        waitForTarget: true,
        placement: "bottom-end",
      },
    ],
  },
  ai: {
    id: "ai",
    label: "AI Assistant",
    version: 4,
    contexts: ["ai"],
    priority: 40,
    steps: [
      {
        id: "ai-assistant",
        target: '[data-tour="ai-assistant"]',
        kind: "informational",
        title: "AI Assistant",
        content: "Work with a project-aware assistant without sending anything during this tour.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "ai-connect-provider",
        target: '[data-tour="ai-connect-provider"]',
        kind: "informational",
        title: "Connect a provider",
        content: "If no provider is configured, start here. The tour never asks for or changes credentials.",
        waitForTarget: true,
      },
      {
        id: "ai-provider-model",
        target: '[data-tour="ai-provider-model"]',
        kind: "informational",
        title: "Provider and model",
        content: "Switch models for this conversation. Changes apply to this session only. Your default model is set in Settings. Logos identify each model's provider.",
        waitForTarget: true,
      },
      {
        id: "ai-prompts",
        target: '[data-tour="ai-prompts"]',
        kind: "informational",
        title: "Prompt shortcuts",
        content: "Choose a ready-made prompt to place it in the chat input.",
        waitForTarget: true,
      },
      {
        id: "ai-persona",
        target: '[data-tour="ai-persona"]',
        kind: "informational",
        title: "Persona",
        content: "Choose how the assistant should work. An active persona replaces your default instructions until you turn it off.",
        waitForTarget: true,
      },
      {
        id: "ai-input",
        target: '[data-tour="ai-input"]',
        kind: "informational",
        title: "Chat input",
        content: "Describe what you need. The assistant can use project context, but this tour never sends a request.",
        waitForTarget: true,
      },
      {
        id: "ai-attachments",
        target: '[data-tour="ai-attachments"]',
        kind: "informational",
        title: "Attachments",
        content: "Attach images, PDFs, and source files when a conversation needs extra context.",
        waitForTarget: true,
      },
      {
        id: "ai-history",
        target: '[data-tour="ai-history"]',
        kind: "informational",
        title: "Conversation history",
        content: "Reopen recent and full chat history while keeping each conversation tied to its project state.",
        waitForTarget: true,
      },
      {
        id: "ai-usage",
        target: '[data-tour="ai-usage"]',
        kind: "informational",
        title: "Usage",
        content: "Configured conversations show run, token, and estimated-cost usage here when available.",
        waitForTarget: true,
      },
      {
        id: "ai-restore",
        target: '[data-tour="ai-restore"]',
        kind: "informational",
        title: "Restore project state",
        content: "After an AI edit, a checkpoint can restore project files without removing the conversation.",
        waitForTarget: true,
      },
    ],
  },
  diagram: {
    id: "diagram",
    label: "Diagram Composer",
    version: 3,
    contexts: ["diagram"],
    priority: 50,
    steps: [
      {
        id: "diagram-composer",
        target: '[data-tour="diagram-composer"]',
        kind: "informational",
        title: "Diagram Composer",
        content: "Build diagrams visually or from TikZ code. The tour does not modify or save your work.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-import",
        target: '[data-tour="diagram-import"]',
        kind: "informational",
        title: "Import a TikZ file",
        content: "Already have a .tikz or .tex file? Import it to replace this starter drawing. It stays a draft until you choose to save it.",
        waitForTarget: true,
      },
      {
        id: "diagram-modes",
        target: '[data-tour="diagram-modes"]',
        kind: "informational",
        title: "Draw and Code",
        content: "Draw mode lets you work directly on the canvas. Code mode shows the generated TikZ and reusable snippets.",
        waitForTarget: true,
      },
      {
        id: "diagram-palette",
        target: '[data-tour="diagram-palette"]',
        kind: "informational",
        title: "Shape palette",
        content: "Choose a shape, then click and drag on the canvas to place and size it.",
        waitForTarget: true,
      },
      {
        id: "diagram-canvas",
        target: '[data-tour="diagram-canvas"]',
        kind: "informational",
        title: "Canvas interactions",
        content: "Move shapes, edit labels, pan with Space and drag, and use the canvas controls to navigate.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-handles",
        target: '[data-tour="diagram-handles"]',
        kind: "informational",
        title: "Connect and resize",
        content: "A selected shape exposes connection and resize handles for precise structure and sizing.",
        waitForTarget: true,
      },
      {
        id: "diagram-inspector",
        target: '[data-tour="diagram-inspector"]',
        kind: "informational",
        title: "Inspector",
        content: "Select a shape or connection to adjust its style, text, routing, and stacking order.",
        waitForTarget: true,
      },
      {
        id: "diagram-preview",
        target: '[data-tour="diagram-preview-affordance"]',
        spotlightTarget: '[data-tour="diagram-preview-panel"]',
        kind: "informational",
        title: "Compiled preview",
        content: "Compile opens a preview beside the editor with scale and background controls.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-compile",
        target: '[data-tour="diagram-compile"]',
        kind: "informational",
        title: "Compile",
        content: "Compile renders an isolated preview without inserting the diagram into your document.",
        waitForTarget: true,
      },
      {
        id: "diagram-save-project",
        target: '[data-tour="diagram-save-project"]',
        kind: "informational",
        title: "Save as project",
        content: "Save a finished diagram as a reusable image project that appears on Home.",
        waitForTarget: true,
      },
      {
        id: "diagram-download",
        target: '[data-tour="diagram-download"]',
        kind: "informational",
        title: "Download",
        content: "Download the compiled diagram as a PNG file without saving it as a project.",
        waitForTarget: true,
      },
    ],
  },
} as const satisfies Record<TourId, TourDefinition>;

export const TOUR_SCHEMA_VERSION = 1;

export function toursForContext(context: TourContext): TourDefinition[] {
  return Object.values(tourRegistry)
    .filter((tour) => (tour.contexts as readonly TourContext[]).includes(context))
    .sort((a, b) => a.priority - b.priority);
}
