// Thin app shim: the editor controller lives in @oleafly/editor.
export {
  setEditorView,
  getEditorView,
  getCurrentLine,
  gotoLine,
  selectWordNearLine,
  gotoRange,
  insertAtCursor,
  replaceRange,
  wrapSelection,
  wrapSelectionOrPlaceholder,
  insertTemplate,
  insertEnvironment,
  focusEditor,
  editorUndo,
  editorRedo,
  editorFind,
  insertText,
} from "@oleafly/editor";
